'use strict';
const $=id=>document.getElementById(id);
const config=window.KGN_CLOUD_CONFIG||{};
const configured=/^https:\/\/[a-z0-9-]+\.supabase\.co$/i.test(config.url||'')&&/^(sb_publishable_|eyJ)/.test(config.publishableKey||'');
let db=null, sessionUser=null, products=[], editId=null, currentImagePath='', selectedFile=null, busy=false;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function status(message,type=''){const el=$('status');el.className='status '+type;el.textContent=message}
function showLogin(){ $('loginPanel').hidden=false; $('adminPanel').hidden=true; $('password').value=''; }
function showAdmin(){ $('loginPanel').hidden=true; $('adminPanel').hidden=false; $('signedInAs').textContent=sessionUser?.email||''; }
function setBusy(isBusy){busy=isBusy;$('saveBtn').disabled=isBusy;$('loginBtn').disabled=isBusy;$('saveSettings').disabled=isBusy;}
function validUrl(path){return path&&/^products\/[0-9a-f-]{36}\.jpg$/.test(path)?db.storage.from('product-photos').getPublicUrl(path).data.publicUrl:'./logo.png'}
function showPhoto(path){$('photoPreview').innerHTML='';if(path){const img=document.createElement('img');img.src=validUrl(path);img.alt='Product photo preview';$('photoPreview').append(img)}}
async function checkOwner(user){if(!user)return false;const {data,error}=await db.from('admin_users').select('user_id').eq('user_id',user.id).maybeSingle();if(error)throw error;return !!data}
async function loadAdmin(){const {data,error}=await db.from('products').select('*').order('updated_at',{ascending:false}).limit(250);if(error)throw error;products=data||[];const ss=await db.from('store_settings').select('festive_enabled').eq('id',1).maybeSingle();if(ss.error)throw ss.error;$('festiveEnabled').checked=ss.data?.festive_enabled!==false;renderList();}
function renderList(){const total=products.length,live=products.filter(p=>p.published).length;$('totalCount').textContent=total;$('liveCount').textContent=live;$('draftCount').textContent=total-live;$('productList').replaceChildren();if(!total){const p=document.createElement('p');p.textContent='अभी Cloud में कोई प्रोडक्ट नहीं है। “नया प्रोडक्ट” चुनें।';$('productList').append(p);return}for(const item of products){const row=document.createElement('div');row.className='item';const photo=document.createElement('img');photo.src=validUrl(item.image_path);photo.alt='';const info=document.createElement('div');const title=document.createElement('strong');title.textContent=item.name_hi||item.name_en||item.name_ur;const sub=document.createElement('small');sub.textContent=[item.category,item.sku,item.published?'Published':'Draft',item.rate===null?'Rate on enquiry':'₹'+item.rate].filter(Boolean).join(' · ');info.append(title,sub);const badge=document.createElement('span');badge.className='badge '+(item.published?'':'draft');badge.textContent=item.published?'LIVE':'DRAFT';const btn=document.createElement('button');btn.type='button';btn.textContent='Edit';btn.onclick=()=>openEditor(item.id);row.append(photo,info,badge,btn);$('productList').append(row)}}
function openEditor(id=null){const p=products.find(x=>x.id===id);editId=p?.id||null;currentImagePath=p?.image_path||'';selectedFile=null;$('photo').value='';$('formTitle').textContent=p?'प्रोडक्ट अपडेट करें':'नया प्रोडक्ट जोड़ें';for(const l of ['hi','en','ur']){$('name_'+l).value=p?.['name_'+l]||'';$('desc_'+l).value=p?.['desc_'+l]||''}$('sku').value=p?.sku||'';$('category').value=p?.category||'ladies';$('rate').value=p?.rate??'';$('sale_rate').value=p?.sale_rate??'';$('moq').value=p?.moq??'';$('unit').value=p?.unit||'piece';$('stock_qty').value=p?.stock_qty??'';$('is_new').checked=!!p?.is_new;$('is_featured').checked=!!p?.is_featured;$('published').checked=!!p?.published;$('archiveBtn').hidden=!p;$('productForm').hidden=false;showPhoto(currentImagePath);$('productForm').scrollIntoView({behavior:'smooth',block:'start'})}
function closeEditor(){$('productForm').hidden=true;editId=null;selectedFile=null;currentImagePath='';$('photo').value=''}
function readNum(id,{integer=false,min=0,max=100000000}={}){const v=$(id).value.trim();if(v==='')return null;const n=Number(v);if(!Number.isFinite(n)||n<min||n>max||(integer&&!Number.isInteger(n)))throw Error('रेट / MOQ / Stock के नंबर सही भरें।');return n}
function formPayload(){const row={sku:$('sku').value.trim(),category:$('category').value,unit:$('unit').value,is_new:$('is_new').checked,is_featured:$('is_featured').checked,published:$('published').checked,updated_at:new Date().toISOString(),image_path:currentImagePath};for(const l of ['hi','en','ur']){row['name_'+l]=$('name_'+l).value.trim();row['desc_'+l]=$('desc_'+l).value.trim()}if(['hi','en','ur'].some(l=>!row['name_'+l]))throw Error('हिन्दी, English और Urdu — तीनों नाम भरें।');row.rate=readNum('rate',{max:99999999});row.sale_rate=readNum('sale_rate',{max:99999999});row.moq=readNum('moq',{integer:true,min:1,max:100000});row.stock_qty=readNum('stock_qty',{integer:true,min:0,max:10000000});if(row.sale_rate!==null&&(row.rate===null||row.sale_rate>=row.rate))throw Error('Sale Rate को सामान्य रेट से कम रखें।');if(row.published&&!row.image_path&&!selectedFile)throw Error('Publish करने से पहले असली product photo चुनें।');return row}
async function imageBlob(file){if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>10*1024*1024)throw Error('केवल JPG/PNG/WebP, अधिकतम 10 MB input।');let bitmap;try{bitmap=await createImageBitmap(file)}catch{throw Error('इस फोटो को पढ़ा नहीं जा सका। दूसरी फोटो चुनें।')}const scale=Math.min(1,1600/Math.max(bitmap.width,bitmap.height));const c=document.createElement('canvas');c.width=Math.max(1,Math.round(bitmap.width*scale));c.height=Math.max(1,Math.round(bitmap.height*scale));const ctx=c.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,c.width,c.height);ctx.drawImage(bitmap,0,0,c.width,c.height);bitmap.close();const blob=await new Promise(resolve=>c.toBlob(resolve,'image/jpeg',.82));if(!blob||blob.size>2*1024*1024)throw Error('Compressed फोटो 2 MB से बड़ी है। छोटी फोटो चुनें।');return blob}
async function saveProduct(e){e.preventDefault();if(busy)return;setBusy(true);let uploaded=null;try{if(!sessionUser)throw Error('फिर से login करें।');const row=formPayload();if(selectedFile){const blob=await imageBlob(selectedFile);uploaded='products/'+crypto.randomUUID()+'.jpg';const up=await db.storage.from('product-photos').upload(uploaded,blob,{contentType:'image/jpeg',upsert:false,cacheControl:'3600'});if(up.error)throw up.error;row.image_path=uploaded}const q=editId?db.from('products').update(row).eq('id',editId).select().single():db.from('products').insert(row).select().single();const {error}=await q;if(error)throw error;status('✓ Product saved in Cloud. Customers will see it after refreshing if Published.','ok');closeEditor();await loadAdmin()}catch(err){console.error(err);status('Save failed: '+(err.message||'Unknown error'),'error');if(uploaded){await db.storage.from('product-photos').remove([uploaded]).catch(()=>{});}}finally{setBusy(false)}}
async function archiveProduct(){if(!editId||busy)return;if(!confirm('यह प्रोडक्ट ग्राहकों से हट जाएगा। जारी रखें?'))return;setBusy(true);try{const {error}=await db.from('products').update({published:false,updated_at:new Date().toISOString()}).eq('id',editId);if(error)throw error;status('Product archived (unpublished).','ok');closeEditor();await loadAdmin()}catch(err){status(err.message||'Archive failed','error')}finally{setBusy(false)}}
async function saveSettings(){if(busy)return;setBusy(true);try{const {error}=await db.from('store_settings').update({festive_enabled:$('festiveEnabled').checked,updated_at:new Date().toISOString()}).eq('id',1);if(error)throw error;status('✓ Seasonal banner setting updated for all customers.','ok')}catch(err){status(err.message||'Settings failed','error')}finally{setBusy(false)}}
async function doLogin(e){e.preventDefault();if(busy)return;setBusy(true);try{const email=$('email').value.trim();const password=$('password').value;const {data,error}=await db.auth.signInWithPassword({email,password});if(error)throw Error('Login failed. Check credentials.');const user=data.user;if(!(await checkOwner(user))){await db.auth.signOut();throw Error('यह account Admin allowlist में नहीं है।')}sessionUser=user;showAdmin();status('✓ Authorized cloud admin login.','ok');await loadAdmin()}catch(err){status(err.message||'Login failed','error');showLogin()}finally{setBusy(false)}}
async function boot(){if(!configured){status('Setup required: cloud-config.js में Supabase URL और publishable key भरें।','error');showLogin();$('loginBtn').disabled=true;return}if(!window.supabase?.createClient){status('Supabase library नहीं मिली। Internet के साथ HTTPS पर पेज खोलें।','error');showLogin();$('loginBtn').disabled=true;return}db=window.supabase.createClient(config.url,config.publishableKey,{auth:{storage:window.sessionStorage,storageKey:'kgn-admin-session',persistSession:true,autoRefreshToken:true,detectSessionInUrl:false}});$('loginForm').addEventListener('submit',doLogin);$('logoutBtn').onclick=async()=>{await db.auth.signOut();sessionUser=null;showLogin();status('Logged out.','ok')};$('newBtn').onclick=()=>openEditor();$('cancelBtn').onclick=closeEditor;$('productForm').addEventListener('submit',saveProduct);$('archiveBtn').onclick=archiveProduct;$('saveSettings').onclick=saveSettings;$('photo').onchange=e=>{selectedFile=e.target.files?.[0]||null;if(selectedFile){if(selectedFile.size>10*1024*1024||!['image/jpeg','image/png','image/webp'].includes(selectedFile.type)){selectedFile=null;e.target.value='';status('Invalid photo type or size.','error');return}const preview=URL.createObjectURL(selectedFile);$('photoPreview').replaceChildren();const img=document.createElement('img');img.src=preview;img.onload=()=>URL.revokeObjectURL(preview);$('photoPreview').append(img)}else showPhoto(currentImagePath)};try{const {data,error}=await db.auth.getUser();if(error||!data?.user){showLogin();status('Owner के email/password से login करें।');return}if(!(await checkOwner(data.user))){await db.auth.signOut();showLogin();status('यह account Admin allowlist में नहीं है।','error');return}sessionUser=data.user;showAdmin();status('✓ Authorized cloud admin login.','ok');await loadAdmin()}catch(err){showLogin();status('Connection failed: '+(err.message||'Check setup'),'error')}}
window.addEventListener('DOMContentLoaded',()=>boot().catch(e=>{console.error(e);status('Setup error.','error');showLogin()}));
