/* Private admin order management; sensitive order data never enters public catalogue rows. */
(()=>{'use strict';const $=id=>document.getElementById(id),stages=['requested','confirmed','packed','shipped','out_for_delivery','delivered'];let rows=[],working=false;
const ui=document.createElement('section');ui.id='kgnOrdersPanel';ui.className='panel';ui.innerHTML='<div class="bar"><h2>Orders · Payment · Tracking</h2><button type="button" class="ghost" id="kgnReloadOrders">Refresh</button></div><p id="kgnOrderAdminMessage" role="status"></p><button type="button" class="ghost" id="kgnCheckPaymentSetup">Razorpay setup जाँचें</button><p id="kgnPaymentSetupMessage" role="status" aria-live="polite" class="foot">Keys और payment mode जाँचें। इससे कोई payment या order नहीं बनता।</p><details><summary>Order settings</summary><p>Online payment के लिए merchant account और webhook setup पहले पूरा करें। COD केवल तभी चालू करें जब आपकी delivery service इसे स्वीकार करती हो।</p><label><input id="kgnOrdersEnabled" type="checkbox"> Customer order requests चालू करें</label><label><input id="kgnOnlineEnabled" type="checkbox"> Online payment (verified merchant account)</label><label><input id="kgnCodEnabled" type="checkbox"> Cash on delivery</label><p>Checkout में customer name, phone और address private database में सेव होते हैं। <a href="./order-privacy.html" target="_blank" rel="noopener">Order privacy notice पढ़ें</a>। इसे स्वीकार करके ही orders चालू करें।</p><button type="button" id="kgnSaveOrderSettings" class="primary">Save order settings</button></details><div id="kgnOrdersList"></div>';
function note(s,error=false){$('kgnOrderAdminMessage').textContent=s;$('kgnOrderAdminMessage').className=error?'status error':'foot'}
function render(){const host=$('kgnOrdersList');host.replaceChildren();if(!rows.length){host.textContent='अभी कोई order नहीं आया।';return}for(const o of rows){const card=document.createElement('details');card.className='order-card';card.innerHTML=`<summary>${esc(o.buyer_name)} · ₹${((o.subtotal_paise+(o.shipping_paise||0))/100).toLocaleString('en-IN')} · ${esc(o.status)}</summary><p>Order: ${esc(o.id)}<br>${esc(new Date(o.created_at).toLocaleString())}</p><p><strong>${esc(o.buyer_name)}</strong> · ${esc(o.phone)}<br>${esc(o.address)}, ${esc(o.city)} ${esc(o.pincode)}</p><p>${o.items.map(x=>`${esc(x.name_hi||x.name)} · ${esc(x.size)} · ${x.quantity} pcs × ₹${x.rate_paise/100}`).join('<br>')}</p><p>Payment: <strong>${esc(o.payment_method)} · ${esc(o.payment_status)}</strong><br>Items subtotal: ₹${o.subtotal_paise/100}${o.shipping_paise===null?' · Shipping pending':' · Shipping: ₹'+o.shipping_paise/100}</p><form data-order="${esc(o.id)}"><label>Next status<select name="status">${o.status==='cancelled'||o.status==='delivered'?`<option value="${o.status}">${o.status}</option>`:`<option value="${stages[stages.indexOf(o.status)+1]}">${stages[stages.indexOf(o.status)+1]}</option>${o.payment_status!=='paid'&&!o.payment_link_id&&['requested','confirmed','packed'].includes(o.status)?'<option value="cancelled">cancelled</option>':''}`}</select></label><label>Delivery charge ₹ (confirm होने पर lock होगा)<input type="number" name="shipping" min="0" max="100000" step="0.01" value="${o.shipping_paise===null?'':o.shipping_paise/100}" ${o.status==='requested'?'':'readonly'}></label><div class="grid2"><label>Courier<input name="courier" maxlength="80" value="${esc(o.courier)}"></label><label>Tracking / AWB number<input name="awb" maxlength="100" value="${esc(o.awb)}"></label></div><label>Courier tracking page (HTTPS, optional)<input name="tracking" type="url" maxlength="500" value="${esc(o.tracking_url)}" placeholder="https://..."></label><p class="foot">Confirm करने से stock reserve होगा। Shipped करने पर inventory में Sale/Dispatch अपने आप होगा; उसी order की manual sale दोबारा न डालें।</p><button type="submit" class="primary" ${['cancelled','delivered'].includes(o.status)?'disabled':''}>Update order</button></form>${o.status==='confirmed'&&o.payment_method==='online'&&o.payment_status==='unpaid'?`<button type="button" class="primary full" data-payment="${esc(o.id)}">${o.payment_link_state==='ready'?'Payment link ready · Refresh':'Create secure payment link'}</button>`:''}${['creating','uncertain'].includes(o.payment_link_state)?'<p class="hint">Gateway reconciliation required: पहले merchant dashboard में इसी order का link जाँचें। Duplicate link बनाने का प्रयास न करें।</p>':''}`;host.append(card)}}
async function load(){if(!db||!sessionUser)return;const {data:cfg,error:cfgError}=await db.from('kgn_commerce_settings').select('*').eq('id',1).maybeSingle();if(cfgError||!cfg){note('Orders backend setup अभी बाकी है। Catalogue listing काम करती रहेगी।',true);$('kgnSaveOrderSettings').disabled=true;return}$('kgnSaveOrderSettings').disabled=false;$('kgnOrdersEnabled').checked=cfg.orders_enabled;$('kgnOnlineEnabled').checked=cfg.online_enabled;$('kgnCodEnabled').checked=cfg.cod_enabled;const {data,error}=await db.from('kgn_orders').select('*').order('created_at',{ascending:false}).limit(100);if(error){note(error.message,true);return}rows=data||[];render();note('Latest '+rows.length+' orders · केवल authorized admin के लिए।')}
function busyOrder(value){working=value;ui.querySelectorAll('button').forEach(b=>b.disabled=value)}
async function update(e){const form=e.target.closest('form[data-order]');if(!form)return;e.preventDefault();if(working)return;const o=rows.find(x=>x.id===form.dataset.order),next=form.elements.status.value;let shipping=null;const raw=form.elements.shipping.value.trim();if(raw){if(!/^\d+(?:\.\d{1,2})?$/.test(raw)){note('Delivery charge सही भरें।',true);return}shipping=Math.round(Number(raw)*100)}if(!confirm('Order '+o.id+' → '+next+'?'+(next==='shipped'?' Stock ledger में dispatch भी save होगा।':'')))return;busyOrder(true);try{const {error}=await db.rpc('kgn_manage_order',{p_id:o.id,p_status:next,p_shipping_paise:shipping,p_courier:form.elements.courier.value.trim(),p_awb:form.elements.awb.value.trim(),p_tracking_url:form.elements.tracking.value.trim()});if(error)throw error;await load();status('✓ Order status updated.','ok')}catch(err){note(err.message||'Order update failed',true)}finally{busyOrder(false)}}
async function checkPaymentSetup(){
 if(working)return;const button=$('kgnCheckPaymentSetup'),message=$('kgnPaymentSetupMessage');
 const show=(text,error=false)=>{message.textContent=text;message.className=error?'status error':'foot'};
 if(!db||!sessionUser){show('पहले Admin Login करें।',true);return}
 working=true;button.disabled=true;show('Razorpay connection जाँचा जा रहा है…');
 try{
  const {data,error}=await db.functions.invoke('kgn-payment',{body:{action:'check_setup'}});
  if(error||data?.error){show('Setup जाँच पूरी नहीं हुई। Admin में दोबारा login करके कोशिश करें।',true);return}
  const mode=data?.mode==='test'?'Test Mode':data?.mode==='live'?'Live Mode':'Mode पहचान नहीं हुई';
  const errors={missing_keys:'Supabase में RAZORPAY_KEY_ID और RAZORPAY_KEY_SECRET दोनों save करें।',invalid_key_format:'Key ID का format सही नहीं है। Razorpay से पूरा Key ID copy करें।',rejected:'Razorpay ने API access स्वीकार नहीं किया। उसी mode की Key ID और Key Secret की जोड़ी जाँचें।',rate_limited:'बहुत अधिक requests हुई हैं। थोड़ी देर बाद जाँचें।',unavailable:'Razorpay तक connection नहीं हुआ। थोड़ी देर बाद जाँचें।'};
  if(data?.api_access!=='ok'){show(mode+' · '+(errors[data?.api_access]||'जाँच पूरी नहीं हुई। दोबारा कोशिश करें।'),true);return}
  if(!data.webhook_secret_configured){show(mode+' · Razorpay keys स्वीकार हुईं। Supabase में RAZORPAY_WEBHOOK_SECRET save करना बाकी है।',true);return}
  show(mode+' · Razorpay keys स्वीकार हुईं। Webhook secret सेव है। Razorpay से payment confirmation का पूरा test अभी बाकी है।'+(data.mode==='test'?' अभी केवल test payments हैं।':' Live keys लगी हैं; इस जाँच से कोई भुगतान नहीं हुआ।'));
 }catch{show('Network या login की समस्या से जाँच पूरी नहीं हुई। दोबारा कोशिश करें।',true)}finally{working=false;button.disabled=false}
}
function install(){$('inventoryPanel').before(ui);$('kgnReloadOrders').onclick=load;$('kgnCheckPaymentSetup').onclick=checkPaymentSetup;ui.addEventListener('submit',update);$('kgnSaveOrderSettings').onclick=async()=>{if(working)return;if($('kgnOrdersEnabled').checked&&!$('kgnOnlineEnabled').checked&&!$('kgnCodEnabled').checked){note('कम से कम एक supported payment method चुनें।',true);return}busyOrder(true);try{const {error}=await db.from('kgn_commerce_settings').update({orders_enabled:$('kgnOrdersEnabled').checked,online_enabled:$('kgnOnlineEnabled').checked,cod_enabled:$('kgnCodEnabled').checked}).eq('id',1);if(error)throw error;note('✓ Order settings saved.')}catch(err){note(err.message,true)}finally{busyOrder(false)}};ui.addEventListener('click',async e=>{const btn=e.target.closest('[data-payment]');if(!btn||working)return;busyOrder(true);try{const {data,error}=await db.functions.invoke('kgn-payment',{body:{id:btn.dataset.payment}});if(error||data?.error)throw Error(data?.error||'Payment gateway setup or request failed. Check merchant setup.');await load();note('✓ Payment link customer tracking में उपलब्ध है।')}catch(err){note(err.message,true)}finally{busyOrder(false)}});const old=window.loadAdmin;window.loadAdmin=async function(...args){await old(...args);await load()};}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();
