'use strict';
const $=id=>document.getElementById(id);
const config=window.KGN_CLOUD_CONFIG||{};
const configured=/^https:\/\/[a-z0-9-]+\.supabase\.co$/i.test(config.url||'')&&/^(sb_publishable_|eyJ)/.test(config.publishableKey||'');
let db=null, sessionUser=null, products=[], editId=null, currentImagePath='', selectedFile=null, busy=false, photoItems=[], gallerySupported=false;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function status(message,type=''){const el=$('status');el.className='status '+type;el.textContent=message}
function showLogin(){ $('loginPanel').hidden=false; $('adminPanel').hidden=true; $('password').value=''; }
function showAdmin(){ $('loginPanel').hidden=true; $('adminPanel').hidden=false; $('signedInAs').textContent=sessionUser?.email||''; }
function setBusy(isBusy){busy=isBusy;$('saveBtn').disabled=isBusy;$('loginBtn').disabled=isBusy;$('saveSettings').disabled=isBusy;$('cancelBtn').disabled=isBusy;$('newBtn').disabled=isBusy;$('archiveBtn').disabled=isBusy;$('logoutBtn').disabled=isBusy;$('photo').disabled=isBusy||photoItems.length>=4;}
let signedPhotos={};
async function loadPrivatePhotos(){const paths=[...new Set(products.flatMap(p=>p.image_paths?.length?p.image_paths:p.image_path?[p.image_path]:[]))];signedPhotos={};if(paths.length){const {data,error}=await db.storage.from('product-photos').createSignedUrls(paths,3600);if(error)throw error;for(const row of data||[])if(row.signedUrl)signedPhotos[row.path]=row.signedUrl;}}
function validUrl(path){if(signedPhotos[path])return signedPhotos[path];return path&&/^products\/[0-9a-f-]{36}\.jpg$/.test(path)?db.storage.from('product-photos').getPublicUrl(path).data.publicUrl:'./logo.png'}
function clearPhotoPreviews(){for(const p of photoItems){if(p.preview)URL.revokeObjectURL(p.preview)}photoItems=[]}
function renderPhotoEditor(){
 const host=$('photoPreview');host.replaceChildren();$('photoCount').textContent=photoItems.length+' / 4 photos';$('photo').disabled=busy||photoItems.length>=4;
 photoItems.forEach((p,i)=>{const box=document.createElement('div');box.className='photo-tile';const img=document.createElement('img');img.src=p.preview||validUrl(p.path);img.alt='Catalogue photo '+(i+1);const label=document.createElement('small');label.textContent=i===0?'Cover photo':'Photo '+(i+1);const actions=document.createElement('div');
 if(i){const cover=document.createElement('button');cover.type='button';cover.textContent='Make cover';cover.disabled=busy;cover.onclick=()=>{if(busy)return;photoItems.unshift(photoItems.splice(i,1)[0]);renderPhotoEditor()};actions.append(cover)}
 const remove=document.createElement('button');remove.type='button';remove.textContent='Remove';remove.setAttribute('aria-label','Remove photo '+(i+1));remove.disabled=busy;remove.onclick=()=>{if(busy)return;const removed=photoItems.splice(i,1)[0];if(removed.preview)URL.revokeObjectURL(removed.preview);renderPhotoEditor()};actions.append(remove);box.append(img,label,actions);host.append(box)});
}
function addPhotos(files){
 if(busy)return;const incoming=Array.from(files||[]);if(photoItems.length+incoming.length>4){status('एक product में अधिकतम 4 photos रख सकते हैं। पहले कोई फोटो हटाएँ।','error');return}
 if(!gallerySupported&&photoItems.length+incoming.length>1){status('4-photo storage के लिए database upgrade पहले लागू करें।','error');return}
 if(incoming.some(f=>!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size>10*1024*1024||!f.size)){status('हर फोटो JPG/PNG/WebP और 10 MB तक होनी चाहिए।','error');return}
 photoItems.push(...incoming.map(file=>({file,preview:URL.createObjectURL(file)})));renderPhotoEditor();
}
function imageId(){if(crypto.randomUUID)return crypto.randomUUID();const bytes=crypto.getRandomValues(new Uint8Array(16));bytes[6]=(bytes[6]&15)|64;bytes[8]=(bytes[8]&63)|128;const h=Array.from(bytes,b=>b.toString(16).padStart(2,'0')).join('');return h.slice(0,8)+'-'+h.slice(8,12)+'-'+h.slice(12,16)+'-'+h.slice(16,20)+'-'+h.slice(20)}
async function checkOwner(user){if(!user)return false;const {data,error}=await db.from('admin_users').select('user_id').eq('user_id',user.id).maybeSingle();if(error)throw error;return !!data}
async function loadAdmin(){const {data,error}=await db.from('products').select('*').order('updated_at',{ascending:false}).limit(250);if(error)throw error;products=data||[];const probe=await db.from('products').select('image_paths,size_original_rates').limit(0);gallerySupported=!probe.error;await loadPrivatePhotos();const ss=await db.from('store_settings').select('festive_enabled').eq('id',1).maybeSingle();if(ss.error)throw ss.error;$('festiveEnabled').checked=ss.data?.festive_enabled!==false;renderList();}
function renderList(){const total=products.length,live=products.filter(p=>p.published).length;$('totalCount').textContent=total;$('liveCount').textContent=live;$('draftCount').textContent=total-live;$('productList').replaceChildren();if(!total){const p=document.createElement('p');p.textContent='अभी Cloud में कोई प्रोडक्ट नहीं है। “नया प्रोडक्ट” चुनें।';$('productList').append(p);return}for(const item of products){const row=document.createElement('div');row.className='item';const photo=document.createElement('img');photo.src=validUrl(item.image_path);photo.alt='';const info=document.createElement('div');const title=document.createElement('strong');title.textContent=item.name_hi||item.name_en||item.name_ur;const sub=document.createElement('small');sub.textContent=[item.category,item.sku,item.published?'Published':'Draft',item.rate===null?'Rate on enquiry':'₹'+item.rate].filter(Boolean).join(' · ');info.append(title,sub);const badge=document.createElement('span');badge.className='badge '+(item.published?'':'draft');badge.textContent=item.published?'LIVE':'DRAFT';const btn=document.createElement('button');btn.type='button';btn.textContent='Edit';btn.onclick=()=>openEditor(item.id);row.append(photo,info,badge,btn);$('productList').append(row)}}
function openEditor(id=null){if(busy)return;const p=products.find(x=>x.id===id);editId=p?.id||null;currentImagePath=p?.image_path||'';selectedFile=null;clearPhotoPreviews();photoItems=(Array.isArray(p?.image_paths)&&p.image_paths.length?p.image_paths:p?.image_path?[p.image_path]:[]).slice(0,4).map(path=>({path}));$('photo').value='';$('formTitle').textContent=p?'प्रोडक्ट अपडेट करें':'नया प्रोडक्ट जोड़ें';for(const l of ['hi','en','ur']){$('name_'+l).value=p?.['name_'+l]||'';$('desc_'+l).value=p?.['desc_'+l]||''}$('sku').value=p?.sku||'';$('category').value=p?.category||'ladies';$('rate').value=p?.rate??'';$('sale_rate').value=p?.sale_rate??'';$('moq').value=p?.moq??'';$('unit').value=p?.unit||'piece';$('stock_qty').value=p?.stock_qty??'';$('is_new').checked=!!p?.is_new;$('is_featured').checked=!!p?.is_featured;$('published').checked=!!p?.published;$('archiveBtn').hidden=!p;$('productForm').hidden=false;renderPhotoEditor();$('productForm').scrollIntoView({behavior:'smooth',block:'start'})}
function closeEditor(){if(busy)return;clearPhotoPreviews();$('productForm').hidden=true;editId=null;selectedFile=null;currentImagePath='';$('photo').value=''}
function readNum(id,{integer=false,min=0,max=100000000}={}){const v=$(id).value.trim();if(v==='')return null;const n=Number(v);if(!Number.isFinite(n)||n<min||n>max||(integer&&!Number.isInteger(n)))throw Error('रेट / MOQ / Stock के नंबर सही भरें।');return n}
function formPayload(){const row={sku:$('sku').value.trim(),category:$('category').value,unit:$('unit').value,is_new:$('is_new').checked,is_featured:$('is_featured').checked,published:$('published').checked,updated_at:new Date().toISOString(),image_path:currentImagePath};for(const l of ['hi','en','ur']){row['name_'+l]=$('name_'+l).value.trim();row['desc_'+l]=$('desc_'+l).value.trim()}if(['hi','en','ur'].some(l=>!row['name_'+l]))throw Error('हिन्दी, English और Urdu — तीनों नाम भरें।');row.rate=readNum('rate',{max:99999999});row.sale_rate=readNum('sale_rate',{max:99999999});row.moq=readNum('moq',{integer:true,min:1,max:100000});if(row.sale_rate!==null&&(row.rate===null||row.sale_rate>=row.rate))throw Error('Sale Rate को सामान्य रेट से कम रखें।');if(row.published&&!photoItems.length)throw Error('Publish करने से पहले असली product photo चुनें।');return row}
async function imageBlob(file){if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>10*1024*1024)throw Error('केवल JPG/PNG/WebP, अधिकतम 10 MB input।');let bitmap;try{bitmap=typeof createImageBitmap==='function'?await createImageBitmap(file):await new Promise((resolve,reject)=>{const url=URL.createObjectURL(file),img=new Image();img.onload=()=>{URL.revokeObjectURL(url);resolve(img)};img.onerror=()=>{URL.revokeObjectURL(url);reject(Error('Invalid photo'))};img.src=url})}catch{throw Error('इस फोटो को पढ़ा नहीं जा सका। दूसरी फोटो चुनें।')}const scale=Math.min(1,1600/Math.max(bitmap.width,bitmap.height));const c=document.createElement('canvas');c.width=Math.max(1,Math.round(bitmap.width*scale));c.height=Math.max(1,Math.round(bitmap.height*scale));const ctx=c.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,c.width,c.height);ctx.drawImage(bitmap,0,0,c.width,c.height);if(bitmap.close)bitmap.close();const blob=await new Promise(resolve=>c.toBlob(resolve,'image/jpeg',.82));if(!blob||blob.size>2*1024*1024)throw Error('Compressed फोटो 2 MB से बड़ी है। छोटी फोटो चुनें।');return blob}
async function saveProduct(e){
 e.preventDefault();if(busy)return;setBusy(true);const uploaded=[];let saved=false;
 try{
  if(!sessionUser)throw Error('फिर से login करें।');
  if(photoItems.length>4)throw Error('Maximum 4 catalogue photos.');
  const row=formPayload();const paths=[];
  if(!gallerySupported&&photoItems.length>1)throw Error('पहले 4-photo database upgrade लागू करें।');
  // Prepare all images before uploading any of them.
  const ready=[];for(const p of photoItems)ready.push(p.file?await imageBlob(p.file):null);
  for(let i=0;i<photoItems.length;i++){const p=photoItems[i];if(p.file){const path='products/'+imageId()+'.jpg';const up=await db.storage.from('product-photos').upload(path,ready[i],{contentType:'image/jpeg',upsert:false,cacheControl:'3600'});if(up.error)throw up.error;uploaded.push(path);paths.push(path)}else paths.push(p.path)}
  row.image_path=paths[0]||'';if(gallerySupported)row.image_paths=paths;
  const q=editId?db.from('products').update(row).eq('id',editId).select().single():db.from('products').insert(row).select().single();
  const {error}=await q;if(error)throw error;saved=true;setBusy(false);closeEditor();
  status('✓ Product और '+paths.length+' photos Cloud में save हो गए।','ok');
  try{await loadAdmin()}catch(err){status('Product save हो गया; सूची refresh नहीं हुई। Refresh करें।','error')}
 }catch(err){status('Save failed: '+(err.message||'Unknown error'),'error');if(!saved&&uploaded.length)await db.storage.from('product-photos').remove(uploaded).catch(()=>{});
 }finally{setBusy(false);renderPhotoEditor()}
}
async function archiveProduct(){if(!editId||busy)return;if(!confirm('यह प्रोडक्ट ग्राहकों से हट जाएगा। जारी रखें?'))return;setBusy(true);try{const {error}=await db.from('products').update({published:false,updated_at:new Date().toISOString()}).eq('id',editId);if(error)throw error;status('Product archived (unpublished).','ok');setBusy(false);closeEditor();await loadAdmin()}catch(err){status(err.message||'Archive failed','error')}finally{setBusy(false)}}
async function saveSettings(){if(busy)return;setBusy(true);try{const {error}=await db.from('store_settings').update({festive_enabled:$('festiveEnabled').checked,updated_at:new Date().toISOString()}).eq('id',1);if(error)throw error;status('✓ Seasonal banner setting updated for all customers.','ok')}catch(err){status(err.message||'Settings failed','error')}finally{setBusy(false)}}
async function doLogin(e){e.preventDefault();if(busy)return;setBusy(true);try{const email=$('email').value.trim();const password=$('password').value;const {data,error}=await db.auth.signInWithPassword({email,password});if(error)throw Error('Login failed. Check credentials.');const user=data.user;if(!(await checkOwner(user))){await db.auth.signOut();throw Error('यह account Admin allowlist में नहीं है।')}sessionUser=user;showAdmin();status('✓ Authorized cloud admin login.','ok');await loadAdmin()}catch(err){status(err.message||'Login failed','error');showLogin()}finally{setBusy(false)}}
async function boot(){if(!configured){status('Setup required: cloud-config.js में Supabase URL और publishable key भरें।','error');showLogin();$('loginBtn').disabled=true;return}if(!window.supabase?.createClient){status('Supabase library नहीं मिली। Internet के साथ HTTPS पर पेज खोलें।','error');showLogin();$('loginBtn').disabled=true;return}db=window.supabase.createClient(config.url,config.publishableKey,{auth:{storage:window.sessionStorage,storageKey:'kgn-admin-session',persistSession:true,autoRefreshToken:true,detectSessionInUrl:false}});$('loginForm').addEventListener('submit',doLogin);$('logoutBtn').onclick=async()=>{await db.auth.signOut();sessionUser=null;showLogin();status('Logged out.','ok')};$('newBtn').onclick=()=>openEditor();$('cancelBtn').onclick=closeEditor;$('productForm').addEventListener('submit',saveProduct);$('archiveBtn').onclick=archiveProduct;$('saveSettings').onclick=saveSettings;$('photo').onchange=e=>{addPhotos(e.target.files);e.target.value=''};try{const {data,error}=await db.auth.getUser();if(error||!data?.user){showLogin();status('Owner के email/password से login करें।');return}if(!(await checkOwner(data.user))){await db.auth.signOut();showLogin();status('यह account Admin allowlist में नहीं है।','error');return}sessionUser=data.user;showAdmin();status('✓ Authorized cloud admin login.','ok');await loadAdmin()}catch(err){showLogin();status('Connection failed: '+(err.message||'Check setup'),'error')}}
window.addEventListener('DOMContentLoaded',()=>boot().catch(e=>{console.error(e);status('Setup error.','error');showLogin()}));
