/* Four catalogue photos, with keyboard, thumbnail and touch navigation. */
(()=>{'use strict';let product=null,index=0,returnFocus=null,startX=null;
const dialog=document.createElement('dialog');dialog.className='kgn-gallery';dialog.setAttribute('aria-labelledby','kgnGalleryTitle');
dialog.innerHTML='<div class="kgn-gallery-head"><strong id="kgnGalleryTitle"></strong><button type="button" id="kgnGalleryClose" aria-label="Close photos">×</button></div><div class="kgn-gallery-stage"><button type="button" id="kgnGalleryPrev" aria-label="Previous photo">‹</button><img id="kgnGalleryImage" alt=""><button type="button" id="kgnGalleryNext" aria-label="Next photo">›</button></div><p id="kgnGalleryCount" aria-live="polite"></p><div id="kgnGalleryThumbs" class="kgn-gallery-thumbs"></div>';
const images=()=>product?.images?.length?product.images.slice(0,4):[product?.image];
function paint(){const all=images();document.getElementById('kgnGalleryTitle').textContent=displayName(product);const image=document.getElementById('kgnGalleryImage');image.src=imgSrc(all[index]);image.alt=displayName(product)+' · '+(index+1);document.getElementById('kgnGalleryCount').textContent=(index+1)+' / '+all.length;const host=document.getElementById('kgnGalleryThumbs');host.replaceChildren();all.forEach((src,i)=>{const button=document.createElement('button');button.type='button';button.setAttribute('aria-label',(lang==='hi'?'फोटो ':lang==='ur'?'تصویر ':'Photo ')+(i+1));button.setAttribute('aria-pressed',String(i===index));const pic=document.createElement('img');pic.src=imgSrc(src);pic.alt='';button.append(pic);button.onclick=()=>{index=i;paint()};host.append(button)});document.getElementById('kgnGalleryPrev').disabled=all.length<2;document.getElementById('kgnGalleryNext').disabled=all.length<2}
function move(delta){index=(index+delta+images().length)%images().length;paint()}
function close(){dialog.close();returnFocus?.focus()}
function install(){document.body.append(dialog);if(typeof dialog.showModal!=='function'&&window.dialogPolyfill)window.dialogPolyfill.registerDialog(dialog);
 document.addEventListener('click',e=>{const trigger=e.target.closest('[data-gallery]');if(!trigger)return;product=products.find(p=>p.id===trigger.dataset.gallery);if(!product)return;returnFocus=trigger;index=0;paint();dialog.showModal()});document.getElementById('kgnGalleryClose').onclick=close;document.getElementById('kgnGalleryPrev').onclick=()=>move(-1);document.getElementById('kgnGalleryNext').onclick=()=>move(1);dialog.addEventListener('click',e=>{if(e.target===dialog)close()});dialog.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();move(e.key==='ArrowLeft'?-1:1)}});dialog.addEventListener('close',()=>returnFocus?.focus());const image=document.getElementById('kgnGalleryImage');image.addEventListener('touchstart',e=>{startX=e.touches.length===1?e.touches[0].clientX:null},{passive:true});image.addEventListener('touchend',e=>{if(startX!==null&&e.changedTouches.length&&Math.abs(e.changedTouches[0].clientX-startX)>45)move(e.changedTouches[0].clientX<startX?1:-1);startX=null},{passive:true});
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();
