/* SMS OTP is verified by Supabase Auth and rechecked by the checkout server.
 * Session and OTP stay in memory; this client never replaces the admin login. */
(()=>{'use strict';
const words={
hi:{optional:'मोबाइल verification वैकल्पिक है। बिना OTP के भी order और payment कर सकते हैं।',checkingService:'OTP की उपलब्धता जाँच रहे हैं…',unavailable:'OTP सेवा अभी उपलब्ध नहीं है। बिना OTP के आगे बढ़ें।',skip:'OTP छोड़ें',send:'OTP भेजें',resend:'OTP दोबारा भेजें',code:'SMS में आया 6 अंकों का OTP',verify:'मोबाइल verify करें',verified:'मोबाइल verified',needed:'भुगतान से पहले मोबाइल OTP verify करें।',sent:'OTP भेजा गया। SMS वाला code भरें।',sending:'OTP भेज रहे हैं…',checking:'OTP जाँच रहे हैं…',failed:'OTP नहीं भेजा जा सका। कुछ देर बाद दोबारा कोशिश करें।',wrong:'OTP गलत या समाप्त है। code जाँचें या नया OTP मँगाएँ।',phone:'10 अंकों का सही मोबाइल नंबर भरें।',wait:'दोबारा OTP भेजने में',seconds:'सेकंड',hint:'आपकी अनुमति से supported फोन पर OTP अपने-आप भर सकता है। चाहें तो SMS से code खुद भरें।',delivery:'Delivery address',contact:'Delivery के लिए मोबाइल',unverified:'मोबाइल नंबर',expired:'मोबाइल verification फिर से करें।'},
en:{optional:'Mobile verification is optional. You can order and pay without an OTP.',checkingService:'Checking OTP availability…',unavailable:'OTP is currently unavailable. You can continue without it.',skip:'Skip OTP',send:'Send OTP',resend:'Resend OTP',code:'6-digit code from SMS',verify:'Verify mobile',verified:'Mobile verified',needed:'Verify your mobile OTP before payment.',sent:'OTP sent. Enter the code from your SMS.',sending:'Sending OTP…',checking:'Checking OTP…',failed:'Could not send OTP. Please try again later.',wrong:'The OTP is incorrect or expired. Check it or request another code.',phone:'Enter a valid 10-digit Indian mobile number.',wait:'Resend available in',seconds:'seconds',hint:'On supported phones, allow the browser to fill the SMS code. You can also enter it yourself.',delivery:'Delivery address',contact:'Mobile for delivery',unverified:'Mobile number',expired:'Please verify your mobile again.'},
ur:{optional:'موبائل کی تصدیق اختیاری ہے۔ OTP کے بغیر بھی آرڈر اور ادائیگی کر سکتے ہیں۔',checkingService:'OTP کی دستیابی جانچ رہے ہیں…',unavailable:'OTP ابھی دستیاب نہیں ہے۔ آپ اس کے بغیر آگے بڑھ سکتے ہیں۔',skip:'OTP چھوڑیں',send:'OTP بھیجیں',resend:'OTP دوبارہ بھیجیں',code:'SMS کا 6 ہندسوں والا OTP',verify:'موبائل کی تصدیق کریں',verified:'موبائل تصدیق شدہ',needed:'ادائیگی سے پہلے موبائل OTP کی تصدیق کریں۔',sent:'OTP بھیج دیا گیا۔ SMS والا کوڈ درج کریں۔',sending:'OTP بھیج رہے ہیں…',checking:'OTP جانچ رہے ہیں…',failed:'OTP نہیں بھیجا جا سکا۔ کچھ دیر بعد دوبارہ کوشش کریں۔',wrong:'OTP غلط ہے یا وقت ختم ہو گیا۔ نیا کوڈ حاصل کریں۔',phone:'درست 10 ہندسوں والا موبائل نمبر درج کریں۔',wait:'دوبارہ OTP بھیجنے میں',seconds:'سیکنڈ',hint:'موزوں فون پر اجازت دینے سے OTP خود بھر سکتا ہے۔ آپ SMS کا کوڈ خود بھی درج کر سکتے ہیں۔',delivery:'ڈیلیوری پتہ',contact:'ڈیلیوری کے لیے موبائل',unverified:'موبائل نمبر',expired:'موبائل کی دوبارہ تصدیق کریں۔'}
};
const $=id=>document.getElementById(id),t=()=>words[document.documentElement.lang]||words.hi;
let client=null,availability=null,availabilityCheck=null,required=false,session=null,verifiedPhone='',sentPhone='',sending=false,verifying=false,generation=0,cooldownUntil=0,controller=null,abortTimer=null,timer=null,onChange=()=>{},message='';
const phone=()=>($('kgnPhone')?.value||'').trim();
const valid=v=>/^[6-9][0-9]{9}$/.test(v);
const normalized=v=>String(v||'').replace(/^\+/,'');
function getToken(value=phone()){return session?.access_token&&verifiedPhone===value&&session.expires_at*1000>Date.now()+30000?session.access_token:''}
function stopAutofill(){controller?.abort();controller=null;clearTimeout(abortTimer);abortTimer=null}
function reset(){generation++;session=null;verifiedPhone='';sentPhone='';sending=false;verifying=false;message='';stopAutofill();if($('kgnOTP'))$('kgnOTP').value='';paint();onChange()}
function auth(){if(!client){const cfg=window.KGN_CLOUD_CONFIG;client=window.supabase.createClient(cfg.url,cfg.publishableKey,{auth:{storageKey:'kgn_checkout_phone_v37',persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}})}return client.auth}
async function checkAvailability(){if(availabilityCheck)return availabilityCheck;availabilityCheck=(async()=>{const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),4000);try{const cfg=window.KGN_CLOUD_CONFIG;if(!cfg?.url||!cfg?.publishableKey)throw Error();const response=await fetch(cfg.url.replace(/\/$/,'')+'/auth/v1/settings',{headers:{apikey:cfg.publishableKey},signal:controller.signal});if(!response.ok)throw Error();const settings=await response.json();availability=settings.external?.phone===true;}catch{availability=false}finally{clearTimeout(timeout);paint()}})();return availabilityCheck}
function preview(){const host=$('kgnDeliveryPreview');if(!host)return;host.replaceChildren();const name=$('kgnBuyer')?.value.trim(),address=$('kgnAddress')?.value.trim(),city=$('kgnCity')?.value.trim(),pin=$('kgnPin')?.value.trim(),number=phone();host.hidden=!([name,address,city,pin,number].some(Boolean));if(host.hidden)return;const title=document.createElement('h3');title.textContent=t().delivery;host.append(title);for(const value of [name,address,[city,pin].filter(Boolean).join(' '),number?`${t().contact}: +91 ${number}`:'']){if(value){const p=document.createElement('p');p.textContent=value;host.append(p)}}if(getToken()){const p=document.createElement('p');p.className='kgn-phone-verified';p.textContent='✓ '+t().verified;host.append(p)}}
function paint(){const panel=$('kgnPhoneVerification');if(!panel)return;panel.hidden=false;$('kgnPhoneOptional').hidden=required;const ok=Boolean(getToken()),remaining=Math.max(0,Math.ceil((cooldownUntil-Date.now())/1000));$('kgnSendOTP').textContent=sentPhone?t().resend:t().send;$('kgnSendOTP').disabled=availability!==true||sending||verifying||remaining>0||ok;$('kgnOTPFields').hidden=ok||!sentPhone||sentPhone!==phone();$('kgnVerifyOTP').disabled=sending||verifying||ok;$('kgnPhoneStatus').textContent=ok?'✓ '+t().verified:message||(availability===null?t().checkingService:availability===false?t().unavailable:required?t().needed:'');$('kgnSkipOTP').hidden=required||!(sentPhone||sending||verifying||ok);$('kgnPhoneStatus').className=ok?'kgn-phone-verified':'';$('kgnOTPCooldown').textContent=remaining?`${t().wait} ${remaining} ${t().seconds}`:'';preview()}
function autofill(number,attempt){stopAutofill();if(!('OTPCredential' in window)||!navigator.credentials?.get)return;controller=new AbortController();const signal=controller.signal;abortTimer=setTimeout(stopAutofill,120000);navigator.credentials.get({otp:{transport:['sms']},signal}).then(otp=>{if(!signal.aborted&&attempt===generation&&phone()===number&&/^\d{6}$/.test(otp?.code||'')&&$('kgnOTP')){$('kgnOTP').value=otp.code;/* Fill only. Never submit the order or payment automatically. */}}).catch(()=>{});}
async function send(){const number=phone();if(availability!==true||sending||verifying||Date.now()<cooldownUntil)return;if(!valid(number)){message=t().phone;paint();return}session=null;verifiedPhone='';sentPhone='';const attempt=++generation;sending=true;message=t().sending;paint();onChange();autofill(number,attempt);
 try{const {error}=await auth().signInWithOtp({phone:'+91'+number,options:{channel:'sms',shouldCreateUser:true}});if(attempt!==generation)return;if(error)throw error;sentPhone=number;cooldownUntil=Date.now()+60000;message=t().sent;}catch{if(attempt===generation){message=t().failed;stopAutofill()}}finally{if(attempt===generation){sending=false;paint();onChange()}}
}
async function verify(){const number=phone(),code=$('kgnOTP')?.value.trim();if(sending||verifying||sentPhone!==number)return;if(!/^\d{6}$/.test(code||'')){message=t().wrong;paint();return}const attempt=generation;verifying=true;message=t().checking;stopAutofill();paint();
 try{const {data,error}=await auth().verifyOtp({phone:'+91'+number,token:code,type:'sms'});if(attempt!==generation||phone()!==number)return;if(error||!data?.session?.access_token||!data.user?.phone_confirmed_at||normalized(data.user.phone)!=='91'+number)throw Error();session=data.session;verifiedPhone=number;$('kgnOTP').value='';message='';}catch{if(attempt===generation){session=null;verifiedPhone='';message=t().wrong}}finally{if(attempt===generation){verifying=false;paint();onChange()}}
}
function attach(options){required=Boolean(options.required);onChange=options.onChange||(()=>{});stopAutofill();const host=$('kgnPhoneVerification');if(!host)return;const w=t();host.innerHTML=`<p id="kgnPhoneOptional">${w.optional}</p><button id="kgnSendOTP" type="button" class="btn btn-outline full">${w.send}</button><p id="kgnOTPCooldown" aria-live="off"></p><div id="kgnOTPFields" hidden><label for="kgnOTP">${w.code}</label><input id="kgnOTP" name="otp" type="text" inputmode="numeric" autocomplete="one-time-code" maxlength="6" autocapitalize="off" spellcheck="false" dir="ltr"><button id="kgnVerifyOTP" type="button" class="btn btn-outline full">${w.verify}</button><p>${w.hint}</p></div><p id="kgnPhoneStatus" role="status"></p><button id="kgnSkipOTP" type="button" class="btn btn-outline full" hidden>${w.skip}</button>`;$('kgnSendOTP').onclick=send;$('kgnVerifyOTP').onclick=verify;$('kgnSkipOTP').onclick=reset;$('kgnPhone').addEventListener('input',reset);for(const id of ['kgnBuyer','kgnAddress','kgnCity','kgnPin'])$(id)?.addEventListener('input',preview);paint();checkAvailability();clearInterval(timer);timer=setInterval(()=>{const had=Boolean(verifiedPhone);if(had&&!getToken()){session=null;verifiedPhone='';message=t().expired;onChange()}paint()},1000);}
window.addEventListener('pagehide',()=>{stopAutofill();clearInterval(timer)});
window.KGNPhone={attach,getToken,preview,needed:()=>required?t().needed:t().optional,invalidate:reset,placeOrder:async args=>{if(!getToken(args.p_buyer?.phone))throw Error(t().needed);auth();return client.rpc('kgn_place_order',args)}};
})();
