/* Guest order requests and private tracking. All totals and transitions are server validated. */
(()=>{'use strict';
const words={hi:{checkout:'ऑर्डर का अनुरोध करें',title:'Delivery और payment',name:'खरीदार / दुकान का नाम',phone:'मोबाइल नंबर',address:'पूरा delivery address',city:'शहर',pin:'पिन कोड',method:'Payment option',online:'Online payment · दुकान की पुष्टि के बाद',cod:'Cash on delivery',consent:'मैं order और delivery के लिए नीचे बताए डेटा उपयोग से सहमत हूँ।',notice:'आपका नाम, फोन, पता और चुने गए सामान दुकान के सुरक्षित order database में सेव होंगे। Order ID और private key इस browser में रखी जाएगी। दुकान पहले stock, shipping और final total की पुष्टि करेगी।',policy:'Order privacy notice पढ़ें',submit:'अनुरोध भेजें',track:'Order tracking',id:'Order ID',key:'Private tracking key',find:'स्थिति देखें',saved:'Order request मिल गया। दुकान की पुष्टि बाकी है।',private:'यह key निजी रखें। दूसरे फोन पर tracking के लिए Order ID और key दोनों चाहिए।',subtotal:'सामान का कुल',shipping:'Delivery charge',total:'Final total',pending:'पुष्टि बाकी',pay:'सुरक्षित payment पेज खोलें',refresh:'स्थिति refresh करें',empty:'पहले product का size और bundle चुनें।',unavailable:'Online ordering अभी चालू नहीं है। दुकान से संपर्क करें।',privacy:'Order privacy notice',status:{requested:'अनुरोध मिला',confirmed:'दुकान ने पुष्टि की',packed:'Packed',shipped:'Courier को दिया',out_for_delivery:'Delivery के लिए निकला',delivered:'Delivered',cancelled:'Cancelled',payment_verified:'Payment verified'},payment:'Payment',paid:'Payment verified',unpaid:'Payment बाकी',cod_due:'Delivery पर भुगतान',carrier:'Courier',courierTrack:'Courier पर tracking खोलें',source:'नीचे की delivery स्थिति दुकान द्वारा अपडेट की जाती है। Courier की ताज़ा स्थिति उसके tracking पेज पर देखें।'},
en:{checkout:'Request an order',title:'Delivery and payment',name:'Buyer / shop name',phone:'Mobile number',address:'Full delivery address',city:'City',pin:'PIN code',method:'Payment option',online:'Online payment · after store confirmation',cod:'Cash on delivery',consent:'I agree to the order and delivery data use described below.',notice:'Your name, phone, address and selected items will be saved in the store’s private order database. Your order ID and private tracking key will be stored in this browser. The store confirms stock, delivery charges and the final total first.',policy:'Read order privacy notice',submit:'Send order request',track:'Order tracking',id:'Order ID',key:'Private tracking key',find:'Track order',saved:'Order request received. Awaiting store confirmation.',private:'Keep this key private. Tracking on another phone needs both the order ID and key.',subtotal:'Items subtotal',shipping:'Delivery charge',total:'Final total',pending:'Awaiting confirmation',pay:'Open secure payment page',refresh:'Refresh status',empty:'Choose a product size and bundle first.',unavailable:'Online ordering is not available yet. Contact the store.',privacy:'Order privacy notice',status:{requested:'Request received',confirmed:'Confirmed by store',packed:'Packed',shipped:'Handed to courier',out_for_delivery:'Out for delivery',delivered:'Delivered',cancelled:'Cancelled',payment_verified:'Payment verified'},payment:'Payment',paid:'Payment verified',unpaid:'Awaiting payment',cod_due:'Pay on delivery',carrier:'Courier',courierTrack:'Open courier tracking',source:'Delivery stages below are updated by the store. Open the courier page for its latest tracking updates.'},
ur:{checkout:'آرڈر کی درخواست کریں',title:'ڈیلیوری اور ادائیگی',name:'خریدار / دکان کا نام',phone:'موبائل نمبر',address:'مکمل ڈیلیوری پتہ',city:'شہر',pin:'پن کوڈ',method:'ادائیگی کا طریقہ',online:'آن لائن · دکان کی تصدیق کے بعد',cod:'ڈیلیوری پر نقد ادائیگی',consent:'میں درج ذیل آرڈر اور ڈیلیوری ڈیٹا کے استعمال سے متفق ہوں۔',notice:'آپ کا نام، فون، پتہ اور منتخب اشیاء دکان کے محفوظ آرڈر ڈیٹا بیس میں محفوظ ہوں گے۔ آرڈر آئی ڈی اور نجی کلید اس براؤزر میں رہیں گی۔ دکان پہلے اسٹاک، ڈیلیوری خرچ اور آخری رقم کی تصدیق کرے گی۔',policy:'آرڈر کی رازداری پڑھیں',submit:'درخواست بھیجیں',track:'آرڈر ٹریکنگ',id:'آرڈر آئی ڈی',key:'نجی ٹریکنگ کلید',find:'حالت دیکھیں',saved:'درخواست موصول ہوئی۔ دکان کی تصدیق باقی ہے۔',private:'یہ کلید نجی رکھیں۔ دوسرے فون پر آرڈر آئی ڈی اور کلید دونوں درکار ہیں۔',subtotal:'اشیاء کی رقم',shipping:'ڈیلیوری خرچ',total:'آخری رقم',pending:'تصدیق باقی',pay:'محفوظ ادائیگی صفحہ کھولیں',refresh:'حالت دوبارہ دیکھیں',empty:'پہلے سائز اور بنڈل منتخب کریں۔',unavailable:'آن لائن آرڈر ابھی دستیاب نہیں۔ دکان سے رابطہ کریں۔',privacy:'آرڈر کی رازداری',status:{requested:'درخواست موصول',confirmed:'دکان نے تصدیق کی',packed:'پیک ہو گیا',shipped:'کوریئر کو دیا',out_for_delivery:'ڈیلیوری کے لیے روانہ',delivered:'پہنچ گیا',cancelled:'منسوخ',payment_verified:'ادائیگی کی تصدیق'},payment:'ادائیگی',paid:'ادائیگی کی تصدیق',unpaid:'ادائیگی باقی',cod_due:'ڈیلیوری پر ادائیگی',carrier:'کوریئر',courierTrack:'کوریئر ٹریکنگ کھولیں',source:'یہ مراحل دکان اپ ڈیٹ کرتی ہے۔ تازہ کوریئر حالت اس کے صفحے پر دیکھیں۔'}};
const t=()=>words[document.documentElement.lang]||words.hi,$=id=>document.getElementById(id),esc=v=>safeText(v);
let cfg=null,current=null,placing=false,pendingToken='',pendingBody='',lastOrder=null;
const KEY='kgn_private_orders_v34';let saved=[];try{const data=JSON.parse(localStorage.getItem(KEY)||'[]');if(Array.isArray(data))saved=data.filter(x=>/^[a-f0-9-]{36}$/.test(x.id)&&/^[a-f0-9]{64}$/.test(x.token)).slice(-20)}catch{}
const statusText=(el,text,error=false)=>{el.textContent=text;el.className=error?'kgn-commerce-error':''};
function safeLink(value,payment=false){try{const u=new URL(value);if(u.protocol!=='https:'||u.username||u.password)return '';if(payment&&!['rzp.io','rzp.pay','razorpay.com'].some(h=>u.hostname===h||u.hostname.endsWith('.'+h)))return '';return u.href}catch{return ''}}
function install(){
 const checkout=document.createElement('section');checkout.id='kgnCheckout';checkout.className='kgn-commerce-box';checkout.hidden=true;checkout.innerHTML='<button id="kgnOpenOrder" type="button" class="btn btn-red full"></button><form id="kgnOrderForm" hidden></form><p id="kgnOrderMessage" role="status"></p><div id="kgnOrderReceipt" class="kgn-order-result"></div>';$('enquiryForm').after(checkout);
 const track=document.createElement('section');track.className='information kgn-commerce-box';track.id='kgnTrackPanel';track.innerHTML='<h3 id="kgnTrackTitle"></h3><form id="kgnTrackForm"><label for="kgnTrackId" id="kgnTrackIdLabel"></label><input id="kgnTrackId" required maxlength="36" autocomplete="off" dir="ltr"><label for="kgnTrackKey" id="kgnTrackKeyLabel"></label><input id="kgnTrackKey" required maxlength="64" autocomplete="off" dir="ltr"><button id="kgnTrackSubmit" class="btn btn-red full" type="submit"></button></form><p id="kgnTrackMessage" role="status"></p><div id="kgnTrackResult" class="kgn-order-result"></div>';$('kgnPrivacyInfo').before(track);
 $('kgnOpenOrder').onclick=()=>{if(!window.KGNBundle?.ready()||!window.KGNBundle.getLines().length){toast(t().empty);return}$('kgnOrderForm').hidden=!$('kgnOrderForm').hidden};
 $('kgnOrderForm').onsubmit=place;$('kgnTrackForm').onsubmit=async e=>{e.preventDefault();await trackOrder($('kgnTrackId').value.trim(),$('kgnTrackKey').value.trim())};
 if(saved.length){$('kgnTrackId').value=saved[saved.length-1].id;$('kgnTrackKey').value=saved[saved.length-1].token}
 translate();const original=window.applyLang;window.applyLang=function(...args){original(...args);translate()};
 const old=window.refreshCloud;window.refreshCloud=async function(...args){await old(...args);await loadConfig()};loadConfig();
}
function translate(){const w=t();$('kgnOpenOrder').textContent=w.checkout;$('kgnTrackTitle').textContent=w.track;$('kgnTrackIdLabel').textContent=w.id;$('kgnTrackKeyLabel').textContent=w.key;$('kgnTrackSubmit').textContent=w.find;
 const form=$('kgnOrderForm'),values={};for(const el of form.elements)if(el.name)values[el.name]=el.type==='checkbox'?el.checked:el.value;
 form.innerHTML=`<h3>${w.title}</h3><label for="kgnBuyer">${w.name}</label><input name="name" id="kgnBuyer" required minlength="2" maxlength="100" autocomplete="name"><label for="kgnPhone">${w.phone}</label><input name="phone" id="kgnPhone" type="tel" required pattern="[6-9][0-9]{9}" maxlength="10" inputmode="numeric" autocomplete="tel-national"><label for="kgnAddress">${w.address}</label><textarea name="address" id="kgnAddress" required minlength="10" maxlength="500" rows="3" autocomplete="street-address"></textarea><label for="kgnCity">${w.city}</label><input name="city" id="kgnCity" required minlength="2" maxlength="100" autocomplete="address-level2"><label for="kgnPin">${w.pin}</label><input name="pincode" id="kgnPin" required pattern="[1-9][0-9]{5}" maxlength="6" inputmode="numeric" autocomplete="postal-code"><label for="kgnPayment">${w.method}</label><select name="payment" id="kgnPayment" required>${cfg?.online_enabled?`<option value="online">${w.online}</option>`:''}${cfg?.cod_enabled?`<option value="cod">${w.cod}</option>`:''}</select><p class="kgn-commerce-note">${w.notice} <a href="./order-privacy.html" target="_blank" rel="noopener">${w.policy} ↗</a></p><label><input type="checkbox" name="consent" required> ${w.consent}</label><button class="btn btn-red full" id="kgnSubmitOrder" type="submit">${w.submit}</button>`;
 for(const el of form.elements)if(el.name&&values[el.name]!==undefined){if(el.type==='checkbox')el.checked=values[el.name];else if(el.tagName!=='SELECT'||Array.from(el.options).some(o=>o.value===values[el.name]))el.value=values[el.name]}
 if(lastOrder)renderOrder($('kgnTrackResult'),lastOrder);
}
async function loadConfig(){if(!sb)return;const {data,error}=await sb.from('kgn_commerce_settings').select('*').eq('id',1).maybeSingle();cfg=error?null:data;$('kgnCheckout').hidden=!(cfg?.orders_enabled&&(cfg.online_enabled||cfg.cod_enabled));translate()}
function token(){return Array.from(crypto.getRandomValues(new Uint8Array(32)),b=>b.toString(16).padStart(2,'0')).join('')}
async function place(e){e.preventDefault();if(placing)return;if(!cfg?.orders_enabled||!sb){toast(t().unavailable);return}const form=$('kgnOrderForm');if(!form.reportValidity())return;
 const lines=window.KGNBundle?.getLines()||[];if(!window.KGNBundle?.ready()||!lines.length){toast(t().empty);return}
 const buyer={name:form.elements.name.value.trim(),phone:form.elements.phone.value.trim(),address:form.elements.address.value.trim(),city:form.elements.city.value.trim(),pincode:form.elements.pincode.value.trim()};const method=form.elements.payment.value;
 const fingerprint=JSON.stringify({buyer,lines,method});if(!pendingToken||pendingBody!==fingerprint){pendingToken=token();pendingBody=fingerprint}
 placing=true;$('kgnSubmitOrder').disabled=true;statusText($('kgnOrderMessage'),'…');
 try{const {data,error}=await sb.rpc('kgn_place_order',{p_buyer:buyer,p_lines:lines,p_payment:method,p_token:pendingToken,p_policy:cfg.policy_version});if(error)throw error;
 current={id:data.id,token:pendingToken};saved=saved.filter(x=>x.id!==current.id).concat(current).slice(-20);try{localStorage.setItem(KEY,JSON.stringify(saved))}catch{}
 $('kgnOrderReceipt').innerHTML=`<p><strong>${t().saved}</strong></p><p>${t().id}</p><code>${esc(current.id)}</code><p>${t().key}</p><code>${esc(current.token)}</code><p>${t().private}</p><button class="btn btn-outline full" type="button" id="kgnGoTrack">${t().track}</button>`;
 $('kgnGoTrack').onclick=()=>{setPage('more');$('kgnTrackId').value=current.id;$('kgnTrackKey').value=current.token;trackOrder(current.id,current.token);$('kgnTrackPanel').scrollIntoView({behavior:'smooth',block:'start'})};
 form.reset();form.hidden=true;statusText($('kgnOrderMessage'),'');pendingToken='';pendingBody='';
 }catch(err){statusText($('kgnOrderMessage'),err.message||'Could not send order. Please retry.',true)}finally{placing=false;$('kgnSubmitOrder').disabled=false}
}
async function trackOrder(id,key){if(!sb){statusText($('kgnTrackMessage'),t().unavailable,true);return}if(!/^[0-9a-f-]{36}$/i.test(id)||!/^[0-9a-f]{64}$/i.test(key)){statusText($('kgnTrackMessage'),'Check Order ID and private key.',true);return}$('kgnTrackSubmit').disabled=true;$('kgnTrackResult').replaceChildren();statusText($('kgnTrackMessage'),'…');try{const {data,error}=await sb.rpc('kgn_track_order',{p_id:id,p_token:key});if(error)throw error;lastOrder=data;renderOrder($('kgnTrackResult'),data);statusText($('kgnTrackMessage'),'')}catch(err){lastOrder=null;statusText($('kgnTrackMessage'),!cfg?t().unavailable:err.message||'Tracking unavailable',true)}finally{$('kgnTrackSubmit').disabled=false}}
function renderOrder(host,o){const w=t(),currency=n=>money(n/100),stages=['requested','confirmed','packed','shipped','out_for_delivery','delivered'];const at=stages.indexOf(o.status),pay=safeLink(o.payment_url,true),courier=safeLink(o.tracking_url);host.innerHTML=`<h3>${esc(w.status[o.status]||o.status)}</h3><p>${esc(new Date(o.created_at).toLocaleString())}</p><dl><dt>${w.subtotal}</dt><dd>${currency(o.subtotal_paise)}</dd><dt>${w.shipping}</dt><dd>${o.shipping_paise===null?w.pending:currency(o.shipping_paise)}</dd><dt>${w.total}</dt><dd>${o.shipping_paise===null?w.pending:currency(o.subtotal_paise+o.shipping_paise)}</dd><dt>${w.payment}</dt><dd>${o.payment_status==='paid'?w.paid:o.payment_method==='cod'?w.cod_due:w.unpaid}</dd></dl><p>${w.source}</p><ol class="kgn-order-timeline">${(o.status==='cancelled'?['requested','cancelled']:stages).map((s,i)=>{const event=o.events.find(x=>x.status===s);return `<li class="${event?'done':''}">${esc(w.status[s])}${event?`<small>${esc(new Date(event.at).toLocaleString())}</small>`:''}</li>`}).join('')}</ol>${o.courier?`<p><strong>${w.carrier}: ${esc(o.courier)}</strong><br>${esc(o.awb)}</p>`:''}${courier?`<a class="btn btn-outline full" href="${esc(courier)}" target="_blank" rel="noopener noreferrer">${w.courierTrack} ↗</a>`:''}${pay&&o.payment_status!=='paid'?`<a class="btn btn-red full" href="${esc(pay)}" target="_blank" rel="noopener noreferrer">${w.pay} ↗</a>`:''}<button type="button" class="btn btn-outline full" id="kgnRefreshOrder">${w.refresh}</button>`;host.querySelector('#kgnRefreshOrder').onclick=()=>trackOrder($('kgnTrackId').value.trim(),$('kgnTrackKey').value.trim())}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();
