/* Account-scoped delivery details and customer-owned receipts. No auth/OTP keys in backups. */
(()=>{'use strict';
const $=id=>document.getElementById(id),PREFIX='kgn_customer_data_v1_',MAX_ORDERS=100;
const words={
 hi:{title:'मेरी जानकारी और backup',remember:'इस फोन पर मेरी delivery details याद रखें',hint:'आपकी अनुमति से नाम, मोबाइल और पता इस फोन में अपने-आप सेव होंगे। साझा फोन पर इसे बंद रखें।',saved:'इस फोन पर सेव है',notSaved:'इस फोन पर सेव करना बंद है',failed:'फोन में डेटा सेव नहीं हुआ। Storage खाली करके फिर कोशिश करें।',download:'Backup download करें',restore:'Backup file वापस लाएँ',forget:'इस फोन की saved जानकारी हटाएँ',confirmForget:'इस account की इस फोन में saved delivery details और receipt copies हटाएँ? Cloud account और orders नहीं हटेंगे।',confirmRestore:'इस backup से इस फोन की saved delivery details बदलें और receipt copies जोड़ें?',restored:'Backup वापस आ गया। Delivery details जाँच लें।',badFile:'यह इस retailer account की सही KGN backup file नहीं है।',exportHint:'Backup में आपकी contact details और सेव की हुई order receipts रहती हैं। इसे निजी रखें। Password, OTP, payment PIN और login/tracking keys शामिल नहीं हैं।',localHint:'App / browser का data मिटने या फोन खोने पर local copy खो सकती है। जरूरी backup download करें।',drive:'Google Drive backup जोड़ें',disconnect:'Drive backup बंद करें',driveReady:'Drive backup जुड़ा है। App खुला होने पर बदलाव अपने-आप भेजे जाएँगे।',driveOff:'Google Drive backup अभी उपलब्ध नहीं है। फिलहाल backup download करके अपनी Drive में रख सकते हैं।',driveFailed:'Drive में backup नहीं हुआ। फोन की copy सुरक्षित है; internet आने पर फिर कोशिश होगी।',driveSaved:'Drive में backup हुआ',driveRestore:'Drive से वापस लाएँ',driveConsent:'नाम, मोबाइल, पता और सेव की हुई order receipts आपके चुने Google Drive account में backup होंगी। अनुमति देना चाहते हैं?',driveDisconnected:'Drive connection बंद हो गया। वहाँ की पुरानी backup copy नहीं मिटाई गई।',noLogin:'Saved details और backup के लिए अपने retailer account में login करें।',receipts:'इस फोन में सेव receipts',noReceipts:'अभी कोई receipt सेव नहीं है। Order tracking खोलने पर उसकी copy यहाँ सेव होगी।',receipt:'Receipt download',retention:'K.G.N. Fashion Zone में Delivered order का विवरण delivery के एक साल बाद automatic सफाई में हटा दिया जाएगा। Cancelled order का विवरण cancellation के एक साल बाद हटेगा। नाम, मोबाइल और पता आपके retailer account में बने रहेंगे। जरूरी receipt अपने पास save करें।',hold:'Refund / dispute या सफाई बंद रहने पर order अधिक समय रह सकता है। सीमित payment reference और जरूरी हिसाब अलग रहते हैं।'},
 en:{title:'My details and backup',remember:'Remember delivery details on this phone',hint:'With your permission, your name, mobile and address save automatically on this phone. Keep this off on a shared phone.',saved:'Saved on this phone',notSaved:'Saving on this phone is off',failed:'Could not save on this phone. Free some storage and try again.',download:'Download backup',restore:'Restore backup file',forget:'Remove saved data from this phone',confirmForget:'Remove this account’s saved delivery details and receipt copies from this phone? Cloud account and orders will remain.',confirmRestore:'Replace saved delivery details and merge receipt copies from this backup?',restored:'Backup restored. Please review the delivery details.',badFile:'This is not a valid KGN backup for this retailer account.',exportHint:'Your backup contains contact details and saved order receipts. Keep it private. Passwords, OTPs, payment PINs and login/tracking keys are excluded.',localHint:'Clearing app/browser data or losing this phone can lose the local copy. Download important backups.',drive:'Connect Google Drive backup',disconnect:'Disconnect Drive backup',driveReady:'Drive backup is connected. Changes are sent automatically while the app is open.',driveOff:'Google Drive backup is not available yet. You can download a backup and keep it in your Drive.',driveFailed:'Drive backup failed. Your phone copy remains; it will retry when online.',driveSaved:'Backed up to Drive',driveRestore:'Restore from Drive',driveConsent:'Your name, mobile, address and saved order receipts will be backed up to the Google Drive account you choose. Continue to authorization?',driveDisconnected:'Drive disconnected. The existing backup in Drive was not deleted.',noLogin:'Log in to your retailer account to use saved details and backup.',receipts:'Receipts saved on this phone',noReceipts:'No saved receipts yet. Opening order tracking saves a copy here.',receipt:'Download receipt',retention:'K.G.N. Fashion Zone automatically removes delivered order details one year after delivery, and cancelled order details one year after cancellation. Your retailer account keeps your name, mobile and address. Save important receipts yourself.',hold:'Orders on a refund/dispute hold, or while cleanup is disabled, may remain longer. Limited payment references and required accounts are kept separately.'},
 ur:{title:'میری معلومات اور بیک اپ',remember:'اس فون پر ڈیلیوری معلومات یاد رکھیں',hint:'آپ کی اجازت سے نام، موبائل اور پتہ اس فون میں خودکار محفوظ ہوں گے۔ مشترکہ فون پر اسے بند رکھیں۔',saved:'اس فون میں محفوظ ہے',notSaved:'اس فون میں محفوظ کرنا بند ہے',failed:'فون میں معلومات محفوظ نہیں ہوئیں۔ جگہ خالی کر کے دوبارہ کوشش کریں۔',download:'بیک اپ ڈاؤن لوڈ کریں',restore:'بیک اپ فائل واپس لائیں',forget:'اس فون کی محفوظ معلومات حذف کریں',confirmForget:'اس اکاؤنٹ کی اس فون میں محفوظ معلومات اور رسیدیں حذف کریں؟ کلاؤڈ اکاؤنٹ اور آرڈرز باقی رہیں گے۔',confirmRestore:'بیک اپ سے ڈیلیوری معلومات بدلیں اور رسیدیں شامل کریں؟',restored:'بیک اپ واپس آ گیا۔ ڈیلیوری معلومات دیکھ لیں۔',badFile:'یہ اس دکاندار اکاؤنٹ کی درست KGN بیک اپ فائل نہیں ہے۔',exportHint:'بیک اپ میں رابطے کی معلومات اور محفوظ رسیدیں ہوتی ہیں۔ اسے نجی رکھیں۔ پاس ورڈ، OTP، ادائیگی PIN اور لاگ ان / ٹریکنگ کلید شامل نہیں۔',localHint:'ایپ / براؤزر کا ڈیٹا صاف کرنے یا فون کھونے سے مقامی کاپی ختم ہو سکتی ہے۔ ضروری بیک اپ ڈاؤن لوڈ کریں۔',drive:'Google Drive بیک اپ جوڑیں',disconnect:'Drive بیک اپ بند کریں',driveReady:'Drive بیک اپ منسلک ہے۔ ایپ کھلی ہونے پر تبدیلیاں خودکار بھیجی جائیں گی۔',driveOff:'Google Drive بیک اپ ابھی دستیاب نہیں۔ بیک اپ ڈاؤن لوڈ کر کے اپنی Drive میں رکھ سکتے ہیں۔',driveFailed:'Drive میں بیک اپ نہیں ہوا۔ فون کی کاپی محفوظ ہے؛ انٹرنیٹ آنے پر دوبارہ کوشش ہوگی۔',driveSaved:'Drive میں بیک اپ ہو گیا',driveRestore:'Drive سے واپس لائیں',driveConsent:'نام، موبائل، پتہ اور محفوظ رسیدیں آپ کے منتخب Google Drive اکاؤنٹ میں بیک اپ ہوں گی۔ اجازت دینا چاہتے ہیں؟',driveDisconnected:'Drive منقطع ہو گئی۔ وہاں کی پرانی بیک اپ کاپی حذف نہیں ہوئی۔',noLogin:'معلومات اور بیک اپ کے لیے اپنے دکاندار اکاؤنٹ میں لاگ ان کریں۔',receipts:'اس فون میں محفوظ رسیدیں',noReceipts:'ابھی کوئی رسید محفوظ نہیں۔ آرڈر ٹریکنگ کھولنے پر کاپی یہاں محفوظ ہوگی۔',receipt:'رسید ڈاؤن لوڈ',retention:'K.G.N. Fashion Zone میں پہنچے ہوئے آرڈر کی تفصیل ڈیلیوری کے ایک سال بعد خودکار حذف ہوگی۔ منسوخ آرڈر منسوخی کے ایک سال بعد حذف ہوگا۔ دکاندار اکاؤنٹ میں نام، موبائل اور پتہ باقی رہیں گے۔ ضروری رسید اپنے پاس محفوظ کریں۔',hold:'ریفنڈ / تنازعہ یا صفائی بند ہونے پر آرڈر زیادہ وقت رہ سکتا ہے۔ محدود ادائیگی حوالہ اور ضروری حساب الگ رہتے ہیں۔'}
};
Object.assign(words.hi,{auto:'अपने-आप Google Drive backup',now:'अभी backup करें',paused:'Automatic backup बंद है।',pending:'बदलाव backup होने बाकी हैं।',busy:'Drive में backup हो रहा है…',last:'आखिरी सफल backup',never:'अभी कोई backup नहीं हुआ',reconnect:'Google की अनुमति खत्म हो गई। Drive दोबारा जोड़ें।',reconnectButton:'Drive दोबारा जोड़ें',loading:'Google लोड हो रहा है…',googleReady:'Google तैयार है। जोड़ने का बटन फिर दबाएँ।',noBackup:'इस account का Drive backup नहीं मिला।',location:'Backup आपकी Drive के निजी app folder में रहता है; सामान्य फाइलों में नहीं दिखता। इसी app से वापस लाएँ।',autoConsent:'इस फोन पर नाम, मोबाइल, पता और receipt copies याद रखें और चुने Google Drive में अपने-आप backup करें? App खुला और internet चालू होने पर backup होगा।',restoreFirst:'नए फोन पर automatic backup चालू करने से पहले पुराना backup वापस ला सकते हैं।',check:'Drive की स्थिति फिर जाँचें',cancelled:'Google अनुमति पूरी नहीं हुई। फिर कोशिश कर सकते हैं।'});
Object.assign(words.en,{auto:'Automatic Google Drive backup',now:'Back up now',paused:'Automatic backup is off.',pending:'Changes are waiting for backup.',busy:'Backing up to Drive…',last:'Last successful backup',never:'No successful backup yet',reconnect:'Google permission has expired. Reconnect Drive.',reconnectButton:'Reconnect Drive',loading:'Loading Google…',googleReady:'Google is ready. Tap connect again.',noBackup:'No Drive backup found for this account.',location:'The backup is in your private Drive app folder, not the normal file list. Restore it through this app.',autoConsent:'Remember your name, mobile, address and receipts on this phone and automatically back them up to your chosen Google Drive? Backup runs while the app is open and online.',restoreFirst:'On a new phone, you can restore your old backup before enabling automatic backup.',check:'Check Drive status again',cancelled:'Google authorization was not completed. You can try again.'});
Object.assign(words.ur,{auto:'خودکار Google Drive بیک اپ',now:'ابھی بیک اپ کریں',paused:'خودکار بیک اپ بند ہے۔',pending:'تبدیلیوں کا بیک اپ باقی ہے۔',busy:'Drive میں بیک اپ ہو رہا ہے…',last:'آخری کامیاب بیک اپ',never:'ابھی کوئی بیک اپ نہیں ہوا',reconnect:'Google کی اجازت ختم ہو گئی۔ Drive دوبارہ جوڑیں۔',reconnectButton:'Drive دوبارہ جوڑیں',loading:'Google لوڈ ہو رہا ہے…',googleReady:'Google تیار ہے۔ جوڑنے کا بٹن دوبارہ دبائیں۔',noBackup:'اس اکاؤنٹ کا Drive بیک اپ نہیں ملا۔',location:'بیک اپ Drive کے نجی ایپ فولڈر میں ہے، عام فائلوں میں نہیں۔ اسی ایپ سے واپس لائیں۔',autoConsent:'نام، موبائل، پتہ اور رسیدیں اس فون پر یاد رکھیں اور منتخب Google Drive میں خودکار بیک اپ کریں؟ ایپ کھلی اور انٹرنیٹ چلنے پر بیک اپ ہوگا۔',restoreFirst:'نئے فون پر خودکار بیک اپ شروع کرنے سے پہلے پرانا بیک اپ واپس لا سکتے ہیں۔',check:'Drive کی حالت دوبارہ دیکھیں',cancelled:'Google کی اجازت مکمل نہیں ہوئی۔ دوبارہ کوشش کر سکتے ہیں۔'});
const t=()=>words[document.documentElement.lang]||words.hi,esc=v=>safeText(v);
const empty=()=>({remember:false,contact:{},orders:[],drive_auto:false,drive_pending:false,drive_last_backup:'',contact_updated_at:''});
let uid='',profile=null,state=empty(),panel,drive=null,driveBusy=false,timer=0,gisPromise,generation=0,revision=0,retryDelay=15000,driveNotice='';
const safe=value=>typeof value==='string'?value:'';
function contact(value={}){return {name:safe(value.name).slice(0,100),phone:safe(value.phone).replace(/\D/g,'').slice(-10),address:safe(value.address).slice(0,500),city:safe(value.city).slice(0,100),pincode:safe(value.pincode).replace(/\D/g,'').slice(0,6)}}
function receipt(value){if(!value||!/^[0-9a-f-]{36}$/i.test(value.id))return null;const items=Array.isArray(value.items)?value.items.slice(0,30).map(x=>({name:safe(x.name).slice(0,200),name_hi:safe(x.name_hi).slice(0,200),name_ur:safe(x.name_ur).slice(0,200),sku:safe(x.sku).slice(0,100),size:safe(x.size).slice(0,30),quantity:Number.isSafeInteger(x.quantity)&&x.quantity>0?x.quantity:0,rate_paise:Number.isSafeInteger(x.rate_paise)&&x.rate_paise>=0?x.rate_paise:0})):[];return {id:value.id,created_at:safe(value.created_at).slice(0,40),status:safe(value.status).slice(0,30),payment_status:safe(value.payment_status).slice(0,30),payment_method:safe(value.payment_method).slice(0,20),subtotal_paise:Number.isSafeInteger(value.subtotal_paise)?value.subtotal_paise:0,shipping_paise:Number.isSafeInteger(value.shipping_paise)?value.shipping_paise:0,items,saved_at:safe(value.saved_at).slice(0,40)||new Date().toISOString()}}
function normalise(value){return {...empty(),remember:value?.remember===true,drive_auto:value?.drive_auto===true,drive_pending:value?.drive_pending===true,drive_last_backup:safe(value?.drive_last_backup).slice(0,40),contact_updated_at:safe(value?.contact_updated_at).slice(0,40),contact:contact(value?.contact),orders:Array.isArray(value?.orders)?value.orders.map(receipt).filter(Boolean).slice(-MAX_ORDERS):[]}}
function snapshot(){return {format:'kgn-customer-backup',version:1,account_id:uid,exported_at:new Date().toISOString(),contact:contact(state.remember?state.contact:fields()),contact_updated_at:state.contact_updated_at,orders:state.orders.map(receipt).filter(Boolean)}}
function message(text,error=false){const el=$('kgnDataStatus');if(el){el.textContent=text;el.className=error?'kgn-commerce-error':'kgn-commerce-note'}}
function persist(notify=true){if(!uid)return false;try{localStorage.setItem(PREFIX+uid,JSON.stringify(state));if(notify)message(state.remember?t().saved:t().notSaved);return true}catch{message(t().failed,true);return false}}
function fields(){const form=$('kgnOrderForm');const value={};for(const key of ['name','phone','address','city','pincode'])value[key]=form?.elements[key]?.value||'';return contact(value)}
function fill(force=false){const form=$('kgnOrderForm');if(!form||!profile)return;const value=state.remember?state.contact:{name:profile.shop_name||profile.contact_name,phone:profile.phone,address:profile.address,city:profile.city};for(const key of ['name','phone','address','city','pincode']){const el=form.elements[key];if(el&&(force||!el.value))el.value=value[key]||'';}form.dispatchEvent(new Event('input',{bubbles:true}));}
function capture(){if(!uid||!state.remember)return;const next=fields();if(JSON.stringify(next)===JSON.stringify(state.contact))return;state.contact=next;state.contact_updated_at=new Date().toISOString();persist();queueDrive()}
function attach(){const form=$('kgnOrderForm');if(!form)return;let row=$('kgnRememberRow');if(!row){row=document.createElement('div');row.id='kgnRememberRow';form.querySelector('#kgnBuyer')?.before(row);}row.innerHTML=`<label><input type="checkbox" id="kgnRememberContact" ${state.remember?'checked':''}> ${esc(t().remember)}</label><p class="kgn-commerce-note">${esc(t().hint)}</p>`;$('kgnRememberContact').disabled=!uid;$('kgnRememberContact').onchange=()=>{state.remember=$('kgnRememberContact').checked;if(state.remember){state.contact=fields();state.contact_updated_at=new Date().toISOString();queueDrive();}else{state.contact={};state.drive_auto=false;clearTimeout(timer);}persist();renderDrive();};fill();}
function render(){if(!panel)return;const w=t();panel.innerHTML=`<h3>${w.title}</h3>${uid?`<p>${w.hint}</p><div class="kgn-data-actions"><button type="button" id="kgnDataDownload" class="btn btn-outline">${w.download}</button><label class="btn btn-outline">${w.restore}<input id="kgnDataImport" type="file" accept="application/json,.json"></label><button type="button" id="kgnDataForget" class="btn btn-outline">${w.forget}</button></div><p class="kgn-commerce-note">${w.exportHint}</p><p class="kgn-commerce-note">${w.localHint}</p><div id="kgnDriveControls"></div><h4>${w.receipts}</h4><div id="kgnLocalReceipts"></div>`:`<p>${w.noLogin}</p>`}<p id="kgnDataStatus" role="status"></p>`;
 if(!uid)return;$('kgnDataDownload').onclick=()=>download(snapshot(),'KGN-customer-backup.json');$('kgnDataImport').onchange=async e=>{const file=e.target.files?.[0];if(!file)return;try{if(file.size>500000)throw Error();await restore(JSON.parse(await file.text()))}catch{message(w.badFile,true)}finally{e.target.value=''}};
 $('kgnDataForget').onclick=()=>{if(!confirm(w.confirmForget))return;state=empty();try{localStorage.removeItem(PREFIX+uid)}catch{};clearTimeout(timer);render();attach();message(w.notSaved)};renderDrive();renderReceipts();
}
function renderReceipts(){const host=$('kgnLocalReceipts');if(!host)return;host.replaceChildren();if(!state.orders.length){host.textContent=t().noReceipts;return;}for(const o of [...state.orders].reverse()){const line=document.createElement('p'),b=document.createElement('button');line.textContent=o.id+' · ₹'+((o.subtotal_paise+o.shipping_paise)/100)+' · '+o.status+' ';b.type='button';b.className='btn btn-outline';b.textContent=t().receipt;b.onclick=()=>download({format:'kgn-order-receipt',version:1,order:o},'KGN-receipt-'+o.id+'.json');line.append(b);host.append(line)}}
function download(data,name){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000)}
async function restore(data){if(!uid||data?.format!=='kgn-customer-backup'||data.version!==1||data.account_id!==uid)throw Error();if(!confirm(t().confirmRestore))return;const incoming=normalise({...data,remember:true}),orders=new Map(state.orders.map(o=>[o.id,o]));for(const o of incoming.orders)orders.set(o.id,o);state={...incoming,drive_auto:state.drive_auto,drive_last_backup:state.drive_last_backup,orders:[...orders.values()].slice(-MAX_ORDERS)};persist();render();fill(true);attach();window.KGNPhone?.invalidate();message(t().restored);queueDrive()}
function saveOrder(order){if(!uid||!state.remember)return;const value=receipt({...order,saved_at:new Date().toISOString()});if(!value)return;state.orders=state.orders.filter(o=>o.id!==value.id).concat(value).slice(-MAX_ORDERS);persist();renderReceipts();queueDrive()}
async function invoke(body){
 if(!sb)throw Error();
 const {data,error}=await sb.functions.invoke('kgn-backup',{body:{...body,account_id:uid},headers:{'X-Requested-With':'KGNBackup'}});
 if(error||data?.error){let details=data;try{if(error?.context)details=await error.context.json()}catch{}const e=Error('Backup request failed');e.code=details?.code||'';throw e;}return data;
}
function driveError(error){
 if(error?.code==='reconnect_required'){drive.reconnect=true;state.drive_auto=false;persist(false);driveNotice=t().reconnect;}
 else driveNotice=error?.code==='no_backup'?t().noBackup:t().driveFailed;
 renderDrive();message(driveNotice,true);
}
function renderDrive(){
 const el=$('kgnDriveControls');if(!el)return;const w=t();
 if(!drive?.available){el.innerHTML=`<p class="kgn-commerce-note">${w.driveOff}</p><button type="button" id="kgnDriveCheck" class="btn btn-outline">${w.check}</button>`;$('kgnDriveCheck').onclick=checkDrive;return;}
 const last=state.drive_last_backup||drive.last_backup_at;
 el.innerHTML=`<h4>Google Drive</h4><p class="kgn-commerce-note">${w.location}</p>${drive.connected?`<label><input type="checkbox" id="kgnDriveAuto" ${state.drive_auto?'checked':''} ${driveBusy?'disabled':''}> ${w.auto}</label><p class="kgn-commerce-note">${state.drive_auto?w.driveReady:w.paused}</p><p class="kgn-commerce-note">${last?w.last+' · '+esc(new Date(last).toLocaleString()):w.never}</p>${!state.drive_auto?`<p class="kgn-commerce-note">${w.restoreFirst}</p>`:''}<div class="kgn-data-actions"><button type="button" id="kgnDriveNow" class="btn btn-outline" ${driveBusy||drive.reconnect?'disabled':''}>${w.now}</button><button type="button" id="kgnDriveRestore" class="btn btn-outline" ${driveBusy?'disabled':''}>${w.driveRestore}</button><button type="button" id="kgnDriveDisconnect" class="btn btn-outline" ${driveBusy?'disabled':''}>${w.disconnect}</button></div>`:''}${!drive.connected||drive.reconnect?`<button type="button" id="kgnDriveConnect" class="btn btn-outline">${drive.reconnect?w.reconnectButton:w.drive}</button>`:''}<p id="kgnDriveStatus" role="status" class="kgn-commerce-note">${esc(driveBusy?w.busy:driveNotice||(state.drive_pending&&state.drive_auto?w.pending:''))}</p>`;
 if($('kgnDriveConnect'))$('kgnDriveConnect').onclick=connect;
 if(!drive.connected)return;
 $('kgnDriveAuto').onchange=()=>{
  const enabled=$('kgnDriveAuto').checked;if(enabled&&!confirm(w.autoConsent)){renderDrive();return;}
  state.drive_auto=enabled;if(enabled){enableLocal();queueDrive();}else clearTimeout(timer);persist(false);driveNotice='';renderDrive();
 };
 $('kgnDriveNow').onclick=()=>{if(!confirm(w.driveConsent))return;enableLocal();queueDrive();flushDrive(true)};
 $('kgnDriveRestore').onclick=async()=>{const run=generation;try{const result=await invoke({action:'restore'});if(run===generation)await restore(result.backup)}catch(e){if(run===generation)driveError(e)}};
 $('kgnDriveDisconnect').onclick=async()=>{
  const run=generation;clearTimeout(timer);driveBusy=true;renderDrive();
  try{await invoke({action:'disconnect'});if(run!==generation)return;state.drive_auto=false;persist(false);drive.connected=false;drive.reconnect=false;driveNotice=w.driveDisconnected;}
  catch(e){if(run===generation)driveError(e)}finally{if(run===generation){driveBusy=false;renderDrive();}}
 };
}
function enableLocal(){if(!state.remember){state.remember=true;state.contact=fields();}persist(false);attach();}
function loadGoogle(){if(window.google?.accounts?.oauth2)return Promise.resolve();if(!gisPromise)gisPromise=new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='https://accounts.google.com/gsi/client';script.async=true;script.onload=resolve;script.onerror=()=>{gisPromise=null;script.remove();reject(Error())};document.head.append(script)});return gisPromise}
function connect(){
 if(!uid||!drive?.client_id)return;const run=generation;
 // requestCode must run directly within a tap, not after fetching the script.
 if(!window.google?.accounts?.oauth2){driveNotice=t().loading;renderDrive();loadGoogle().then(()=>{if(run===generation){driveNotice=t().googleReady;renderDrive()}}).catch(e=>{if(run===generation)driveError(e)});return;}
 if(!confirm(t().autoConsent))return;
 const c=google.accounts.oauth2.initCodeClient({client_id:drive.client_id,scope:'https://www.googleapis.com/auth/drive.appdata',include_granted_scopes:false,ux_mode:'popup',select_account:true,callback:async response=>{
  if(run!==generation)return;if(!response.code){driveNotice=t().cancelled;renderDrive();return;}
  try{await invoke({action:'connect',code:response.code,consent:true});if(run!==generation)return;drive.connected=true;drive.reconnect=false;driveNotice='';enableLocal();state.drive_auto=true;queueDrive();renderDrive();}
  catch(e){if(run===generation)driveError(e)}
 },error_callback:()=>{if(run===generation){driveNotice=t().cancelled;renderDrive();}}});c.requestCode();
}
function queueDrive(mark=true,delay=5000){
 clearTimeout(timer);if(!uid)return;if(mark){revision++;state.drive_pending=true;persist(false);}
 if(drive?.connected&&state.drive_auto&&state.remember&&state.drive_pending&&!drive.reconnect)timer=setTimeout(()=>flushDrive(),delay);
 renderDrive();
}
async function flushDrive(manual=false){
 if(!uid||!drive?.connected||drive.reconnect||driveBusy||!navigator.onLine||(!manual&&(document.hidden||!state.drive_auto||!state.remember||!state.drive_pending)))return;
 clearTimeout(timer);driveBusy=true;driveNotice='';const run=generation,sentRevision=revision;renderDrive();let failed=false;
 try{const result=await invoke({action:'save',backup:snapshot()});if(run!==generation)return;state.drive_pending=revision!==sentRevision;state.drive_last_backup=result.saved_at||new Date().toISOString();retryDelay=15000;persist(false);driveNotice=t().driveSaved;}
 catch(e){failed=true;if(run===generation){driveError(e);retryDelay=Math.min(retryDelay*2,300000);}}
 finally{if(run===generation){driveBusy=false;renderDrive();if(state.drive_pending)queueDrive(false,failed?retryDelay:5000);}}
}
async function checkDrive(){
 if(!uid)return;const run=generation;try{const d=await invoke({action:'status'});if(run!==generation)return;drive=d;renderDrive();if(d.available)queueDrive(false);}
 catch(e){if(run===generation)message(t().driveFailed,true)}
}
async function account(next){
 const nextId=next?.user_id||'';profile=next;if(nextId===uid){attach();return;}generation++;revision=0;retryDelay=15000;clearTimeout(timer);uid=nextId;drive=null;driveBusy=false;driveNotice='';state=empty();
 const form=$('kgnOrderForm');if(form){form.reset();for(const k of ['name','phone','address','city','pincode'])if(form.elements[k])form.elements[k].value='';}window.KGNPhone?.invalidate();
 if(uid){try{state=normalise(JSON.parse(localStorage.getItem(PREFIX+uid)||'{}'))}catch{}}
 render();attach();if(uid)await checkDrive();
}
function install(){panel=document.createElement('section');panel.className='information kgn-commerce-box';panel.id='kgnCustomerData';$('kgnPrivacyInfo').before(panel);render();document.addEventListener('kgn:retailer-profile',e=>account(e.detail));document.addEventListener('kgn:checkout-form',attach);document.addEventListener('input',e=>{if(e.target.closest?.('#kgnOrderForm')&&['name','phone','address','city','pincode'].includes(e.target.name))capture()});document.addEventListener('change',e=>{if(e.target.closest?.('#kgnOrderForm')&&['name','phone','address','city','pincode'].includes(e.target.name))capture()});window.addEventListener('online',()=>{if(drive?.available)queueDrive(false,0);else checkDrive()});document.addEventListener('visibilitychange',()=>{if(!document.hidden)queueDrive(false,0)});window.addEventListener('pagehide',()=>{if(state.remember)capture()});const lang=window.applyLang;window.applyLang=function(...args){lang(...args);render();attach()};account(window.KGNRetailer?.profile());}
window.KGNCustomerData={attach,capture,saveOrder,retentionNotice:()=>t().retention+' '+t().hold};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();
