/* Retailer identity is separate from the admin session and optional delivery OTP. */
(()=>{'use strict';
const words={
 hi:{account:'दुकानदार account',unlock:'थोक भाव देखने के लिए login करें',intro:'सिर्फ दुकानदार / retailer के लिए। दुकान की जानकारी और फोटो भेजें; मंज़ूरी के बाद थोक भाव और सीधा payment खुलेंगे।',login:'Login करें',register:'दुकानदार registration',phone:'मोबाइल नंबर',password:'Password',newPassword:'Password · कम से कम 10 अक्षर, एक English अक्षर और अंक',shop:'दुकान का नाम',name:'आपका नाम',address:'दुकान का पूरा पता',city:'शहर / मार्केट',gst:'GST नंबर · वैकल्पिक',proof:'दुकान की फोटो या visiting card',consent:'मैं दुकानदार हूँ और आवेदन की जाँच के लिए ये जानकारी व फोटो देने से सहमत हूँ।',send:'मंज़ूरी के लिए आवेदन भेजें',pending:'आपका आवेदन मिला है। दुकान की मंज़ूरी का इंतज़ार करें।',approved:'दुकानदार account approved · थोक भाव उपलब्ध हैं',rejected:'आवेदन स्वीकार नहीं हुआ। दुकान से संपर्क करें।',blocked:'इस account का access बंद है। दुकान से संपर्क करें।',refresh:'स्थिति फिर जाँचें',logout:'Logout',close:'बंद करें',busy:'कृपया प्रतीक्षा करें…',failed:'काम पूरा नहीं हुआ। जानकारी और internet जाँचकर दोबारा कोशिश करें।',loginError:'मोबाइल या password सही नहीं है।',saved:'आवेदन भेज दिया है। अब मोबाइल और password से login करें।',privacy:'जानकारी केवल दुकान के admin और आपको दिखाई देगी। Registration से मोबाइल OTP verified नहीं होता।',forgot:'Password भूल गए? दुकान से संपर्क करें।',contact:'दुकान से संपर्क करें',limit:'बहुत बार कोशिश हुई है। कुछ देर बाद फिर कोशिश करें।',exists:'Account नहीं बन पाया। पहले registration किया है तो login करें।',photoError:'दुकान की JPG, PNG या WebP फोटो चुनें, अधिकतम 10 MB।',locked:'थोक भाव · approved दुकानदारों के लिए',review:'Admin की सूचना',change:'Password बदलें',changed:'Password बदल गया।',changeHint:'नया password भरें; कम से कम 10 अक्षर और अंक।'},
 en:{account:'Retailer account',unlock:'Log in to view wholesale prices',intro:'For shopkeepers and retailers. Submit your shop details and photo. Store approval unlocks wholesale prices and direct payment.',login:'Log in',register:'Register as a retailer',phone:'Mobile number',password:'Password',newPassword:'Password · at least 10 characters, one English letter and number',shop:'Shop name',name:'Your name',address:'Full shop address',city:'City / market',gst:'GST number · optional',proof:'Shop photo or visiting card',consent:'I am a retailer and consent to sharing these details and photo for application review.',send:'Submit for approval',pending:'Application received. Awaiting store approval.',approved:'Retailer approved · wholesale prices unlocked',rejected:'Application declined. Contact the store.',blocked:'Account access is blocked. Contact the store.',refresh:'Check status',logout:'Log out',close:'Close',busy:'Please wait…',failed:'Could not finish. Check your details and internet, then try again.',loginError:'Incorrect mobile number or password.',saved:'Application sent. Log in with your mobile and password.',privacy:'Your details are visible only to you and the store admin. Registration does not verify your mobile by OTP.',forgot:'Forgot your password? Contact the store.',contact:'Contact the store',limit:'Too many attempts. Please try again later.',exists:'Account could not be created. If already registered, log in.',photoError:'Choose a JPG, PNG or WebP shop photo, up to 10 MB.',locked:'Wholesale prices · approved retailers only',review:'Store note',change:'Change password',changed:'Password changed.',changeHint:'Enter a new password with at least 10 characters, a letter and a number.'},
 ur:{account:'دکاندار اکاؤنٹ',unlock:'ہول سیل ریٹ دیکھنے کے لیے لاگ ان کریں',intro:'صرف دکاندار اور ریٹیلر کے لیے۔ دکان کی معلومات اور تصویر بھیجیں۔ منظوری کے بعد ہول سیل ریٹ اور براہ راست ادائیگی دستیاب ہوں گے۔',login:'لاگ ان کریں',register:'دکاندار رجسٹریشن',phone:'موبائل نمبر',password:'پاس ورڈ',newPassword:'پاس ورڈ · کم از کم 10 حروف، ایک انگریزی حرف اور عدد',shop:'دکان کا نام',name:'آپ کا نام',address:'دکان کا مکمل پتہ',city:'شہر / مارکیٹ',gst:'GST نمبر · اختیاری',proof:'دکان کی تصویر یا وزٹنگ کارڈ',consent:'میں دکاندار ہوں اور درخواست کی جانچ کے لیے یہ معلومات اور تصویر دینے پر رضامند ہوں۔',send:'منظوری کے لیے درخواست بھیجیں',pending:'درخواست موصول ہوئی۔ دکان کی منظوری کا انتظار کریں۔',approved:'دکاندار منظور شدہ · ہول سیل ریٹ دستیاب ہیں',rejected:'درخواست قبول نہیں ہوئی۔ دکان سے رابطہ کریں۔',blocked:'اکاؤنٹ تک رسائی بند ہے۔ دکان سے رابطہ کریں۔',refresh:'حالت دوبارہ دیکھیں',logout:'لاگ آؤٹ',close:'بند کریں',busy:'براہ کرم انتظار کریں…',failed:'کام مکمل نہیں ہوا۔ معلومات اور انٹرنیٹ چیک کر کے دوبارہ کوشش کریں۔',loginError:'موبائل یا پاس ورڈ درست نہیں۔',saved:'درخواست بھیج دی گئی۔ موبائل اور پاس ورڈ سے لاگ ان کریں۔',privacy:'معلومات صرف آپ اور دکان کے ایڈمن کو نظر آئیں گی۔ رجسٹریشن سے موبائل OTP تصدیق نہیں ہوتا۔',forgot:'پاس ورڈ بھول گئے؟ دکان سے رابطہ کریں۔',contact:'دکان سے رابطہ کریں',limit:'بہت زیادہ کوششیں ہوئیں۔ کچھ دیر بعد دوبارہ کوشش کریں۔',exists:'اکاؤنٹ نہیں بن سکا۔ پہلے رجسٹریشن کی ہے تو لاگ ان کریں۔',photoError:'دکان کی JPG، PNG یا WebP تصویر منتخب کریں، زیادہ سے زیادہ 10 MB۔',locked:'ہول سیل ریٹ · صرف منظور شدہ دکانداروں کے لیے',review:'دکان کا پیغام',change:'پاس ورڈ بدلیں',changed:'پاس ورڈ بدل گیا۔',changeHint:'کم از کم 10 حروف، ایک حرف اور عدد والا نیا پاس ورڈ درج کریں۔'}
};
const $=id=>document.getElementById(id),t=()=>words[document.documentElement.lang]||words.hi;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let profile=null,approved=false,rows=[],mode='login',working=false,installed=false,refreshing=null,epoch=0,dialogView=null;
const dialog=document.createElement('dialog');dialog.id='kgnRetailerDialog';dialog.className='kgn-retailer-dialog';
function message(text,error=false){const el=$('kgnRetailerMessage');if(el){el.textContent=text;el.className=error?'kgn-commerce-error':'';}}
function paint(){if(!installed)return;const w=t();$('kgnRetailerAccount').textContent=approved?'✓ '+w.account:w.account;const banner=$('kgnRetailerBanner');banner.querySelector('strong').textContent=approved?w.approved:profile?w[profile.status]||w.pending:w.locked;banner.querySelector('button').textContent=profile?w.account:w.unlock;banner.classList.toggle('approved',approved);if(!dialog.open)return;
 // Photo pickers trigger visibility/focus refreshes. Keep the existing form and
 // native file input mounted unless the account view actually changes.
 const view=JSON.stringify([document.documentElement.lang,profile?[profile.user_id,profile.status,profile.shop_name,profile.phone,profile.review_note]:mode]);
 if(view===dialogView)return;
 dialogView=view;
 const input=(id,label,type='text',extra='')=>`<label for="${id}">${label}</label><input id="${id}" name="${id}" type="${type}" ${extra}>`;
 dialog.innerHTML=`<div class="kgn-retailer-head"><h2>${w.account}</h2><button type="button" id="kgnRetailerClose" aria-label="${w.close}">×</button></div><div class="kgn-retailer-body">${profile?`<h3>${esc(profile.shop_name)}</h3><p class="kgn-retailer-state">${w[profile.status]||w.pending}</p>${profile.review_note?`<p>${w.review}: ${esc(profile.review_note)}</p>`:''}<p dir="ltr">${esc(profile.phone)}</p><button id="kgnRetailerRefresh" class="btn btn-red full" type="button">${w.refresh}</button><button id="kgnRetailerChange" class="btn btn-outline full" type="button">${w.change}</button><form id="kgnRetailerPasswordForm" hidden>${input('kgnRetailerNewPassword',w.changeHint,'password','required minlength="10" maxlength="72" autocomplete="new-password"')}<button class="btn btn-red full" type="submit">${w.change}</button></form><button id="kgnRetailerLogout" class="btn btn-outline full" type="button">${w.logout}</button>`:`<p>${w.intro}</p><div class="kgn-retailer-tabs"><button type="button" data-retailer-mode="login" aria-pressed="${mode==='login'}">${w.login}</button><button type="button" data-retailer-mode="register" aria-pressed="${mode==='register'}">${w.register}</button></div><form id="kgnRetailerForm">${input('kgnRetailerPhone',w.phone,'tel','required pattern="[6-9][0-9]{9}" maxlength="10" inputmode="numeric" autocomplete="username" dir="ltr"')}${input('kgnRetailerPassword',mode==='register'?w.newPassword:w.password,'password',`required minlength="${mode==='register'?10:1}" maxlength="72" autocomplete="${mode==='register'?'new-password':'current-password'}"`)}${mode==='register'?`${input('kgnRetailerShop',w.shop,'text','required minlength="2" maxlength="100" autocomplete="organization"')}${input('kgnRetailerName',w.name,'text','required minlength="2" maxlength="100" autocomplete="name"')}<label for="kgnRetailerAddress">${w.address}</label><textarea id="kgnRetailerAddress" required minlength="10" maxlength="500" autocomplete="street-address"></textarea>${input('kgnRetailerCity',w.city,'text','required minlength="2" maxlength="100" autocomplete="address-level2"')}${input('kgnRetailerGST',w.gst,'text','pattern="[A-Za-z0-9]{15}" maxlength="15" autocapitalize="characters"')}${input('kgnRetailerProof',w.proof,'file','required accept="image/jpeg,image/png,image/webp"')}<label class="kgn-retailer-consent"><input id="kgnRetailerConsent" type="checkbox" required> ${w.consent}</label><p class="kgn-retailer-fine">${w.privacy} <a href="./order-privacy.html#retailer" target="_blank" rel="noopener">Privacy notice ↗</a></p>`:''}<button class="btn btn-red full" type="submit">${mode==='register'?w.send:w.login}</button></form><p class="kgn-retailer-fine">${w.forgot}</p>`}<p id="kgnRetailerMessage" role="status"></p><a href="tel:+917905275441">${w.contact}</a></div>`;
 $('kgnRetailerClose').onclick=()=>dialog.close();dialog.querySelectorAll('[data-retailer-mode]').forEach(b=>b.onclick=()=>{if(working)return;mode=b.dataset.retailerMode;paint()});
 if($('kgnRetailerForm'))$('kgnRetailerForm').onsubmit=submit;
 if(profile){$('kgnRetailerRefresh').onclick=refresh;$('kgnRetailerLogout').onclick=logout;$('kgnRetailerChange').onclick=()=>{$('kgnRetailerPasswordForm').hidden=false;$('kgnRetailerNewPassword').focus()};$('kgnRetailerPasswordForm').onsubmit=async e=>{e.preventDefault();if(working)return;const password=$('kgnRetailerNewPassword').value;if(!validPassword(password)){message(w.changeHint,true);return;}lock(true);try{const {error}=await sb.auth.updateUser({password});if(error)throw error;$('kgnRetailerPasswordForm').hidden=true;$('kgnRetailerNewPassword').value='';message(w.changed);}catch{message(w.failed,true)}finally{lock(false)}};}
 lock(working);
}
function lock(value){working=value;dialog.querySelectorAll('button,input,textarea').forEach(el=>{if(el.id!=='kgnRetailerClose')el.disabled=value})}
function validPassword(p){return p.length>=10&&p.length<=72&&/[A-Za-z]/.test(p)&&/[0-9]/.test(p)}
async function photo(file){if(!file||!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>10485760)throw Error('photo');const url=URL.createObjectURL(file);try{const img=await new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=reject;i.src=url});const factor=Math.min(1,1400/Math.max(img.width,img.height)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.width*factor));canvas.height=Math.max(1,Math.round(img.height*factor));const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height);const data=canvas.toDataURL('image/jpeg',.82);if(data.length>2600000)throw Error('photo');return data;}finally{URL.revokeObjectURL(url)}}
async function invoke(body){const result=await sb.functions.invoke('kgn-retailers',{body});let data=result.data;if(result.error?.context){try{data=await result.error.context.clone().json()}catch{}}if(result.error||data?.error)throw Error(data?.error||'Connection failed');return data;}
async function submit(e){e.preventDefault();if(working||!sb)return;const w=t(),phone=$('kgnRetailerPhone').value.trim(),password=$('kgnRetailerPassword').value;if(mode==='register'&&!validPassword(password)){message(w.newPassword,true);return;}const body=mode==='register'?{action:'register',phone,password,shop_name:$('kgnRetailerShop').value.trim(),contact_name:$('kgnRetailerName').value.trim(),address:$('kgnRetailerAddress').value.trim(),city:$('kgnRetailerCity').value.trim(),gst:$('kgnRetailerGST').value.trim(),consent:$('kgnRetailerConsent').checked}:null,file=$('kgnRetailerProof')?.files?.[0];lock(true);message(w.busy);
 try{if(body){body.proof=await photo(file);const data=await invoke(body);if(!data.session){mode='login';paint();message(w.saved);return;}const result=await sb.auth.setSession(data.session);if(result.error)throw result.error;}else{const {error}=await sb.auth.signInWithPassword({email:'retailer.'+phone+'@kgn-login.invalid',password});if(error)throw Error('login');}await refresh();}catch(error){const s=String(error.message||'');message(s==='photo'?w.photoError:s==='login'?w.loginError:/Too many/.test(s)?w.limit:/Account could not/.test(s)?w.exists:w.failed,true);}finally{lock(false)}
}
async function catalog(){const serial=++epoch;try{const data=await invoke({action:'catalog'});if(serial!==epoch)return rows;const was=approved;profile=data.profile||null;approved=data.approved===true;rows=Array.isArray(data.products)?data.products:[];if(was&&!approved)closeProductDialogs();paint();return rows;}catch(error){if(serial===epoch){approved=false;profile=null;rows=[];closeProductDialogs();paint();}throw error;}}
function closeProductDialogs(){for(const id of ['kgnBundleDialog','kgnGalleryDialog']){const el=$(id);if(el?.open)el.close()}document.querySelectorAll('dialog.kgn-gallery[open]').forEach(el=>el.close());}
async function refresh(){if(refreshing)return refreshing;refreshing=(async()=>{await window.refreshCloud();paint();})().finally(()=>{refreshing=null});return refreshing;}
async function logout(){if(working)return;lock(true);epoch++;approved=false;profile=null;rows=[];products=[];closeProductDialogs();renderAll();try{await sb.auth.signOut({scope:'local'});await refresh();}finally{lock(false);paint()}}
function open(){if(!installed)return;if(!dialog.open)dialog.showModal();paint();$('kgnRetailerPhone')?.focus()}
function decorate(){if(!installed)return;document.querySelectorAll('.product-card').forEach(card=>{if(approved)return;const price=card.querySelector('.price-row');if(price)price.textContent=t().locked;const add=card.querySelector('[data-add]');if(add)add.textContent=t().unlock;card.querySelector('.ribbon.sale')?.remove()});}
function install(){installed=true;document.body.append(dialog);if(typeof dialog.showModal!=='function'&&window.dialogPolyfill)window.dialogPolyfill.registerDialog(dialog);const banner=document.createElement('section');banner.id='kgnRetailerBanner';banner.className='kgn-retailer-banner';banner.innerHTML='<strong></strong><button class="btn btn-outline" type="button"></button>';$('homeCategories').closest('section')?.before(banner);if(!banner.isConnected)$('home').prepend(banner);banner.querySelector('button').onclick=open;const account=document.createElement('button');account.id='kgnRetailerAccount';account.className='btn btn-red full';account.type='button';account.onclick=open;$('more').prepend(account);const old=window.renderAll;window.renderAll=function(...args){old(...args);decorate()};const cards=window.renderCards;window.renderCards=function(...args){cards(...args);decorate()};const lang=window.applyLang;window.applyLang=function(...args){lang(...args);paint()};paint();document.addEventListener('visibilitychange',()=>{if(!document.hidden&&sb)refresh()});setInterval(()=>{if(!document.hidden&&sb&&profile)refresh()},60000);}
window.KGNRetailer={catalog,rows:()=>rows,allowed:()=>approved,profile:()=>profile,open,refresh,locked:()=>t().locked};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();
