const {JSDOM}=require('jsdom');const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const root=path.join(__dirname,'..');const read=f=>fs.readFileSync(path.join(root,f),'utf8');
(async()=>{
 const dom=new JSDOM(read('admin.html'),{url:'https://example.test/admin.html',runScripts:'outside-only',pretendToBeVisual:true});const w=dom.window;w.eval=code=>require('node:vm').runInContext(code,dom.getInternalVMContext());await new Promise(r=>w.setTimeout(r,0));w.HTMLElement.prototype.scrollIntoView=()=>{};w.URL.createObjectURL=()=> 'blob:test';w.URL.revokeObjectURL=()=>{};w.alert=()=>{};w.confirm=()=>true;w.eval(read('admin.js'));w.eval('gallerySupported=true;products=[];sessionUser={id:"admin"};');w.eval(read('admin-bundles.js'));w.openEditor();
 for(const lang of ['hi','en','ur'])w.document.getElementById('name_'+lang).value='Test '+lang;
 w.document.querySelector('[data-size="S"]').click();w.document.querySelector('[data-pack="3"]').click();
 const input=(selector,value)=>{const el=w.document.querySelector(selector);el.value=value;el.dispatchEvent(new w.Event('input',{bubbles:true}))};input('[data-rate-size="S"]','100');input('[data-original-size="S"]','200');
 let p=w.formPayload();assert.equal(p.size_rates.S,100);assert.equal(p.size_original_rates.S,200);assert.ok(!('stock_qty' in p));
 input('[data-original-size="S"]','99');assert.throws(()=>w.formPayload(),/Actual price/);input('[data-original-size="S"]','200');
 const files=Array.from({length:4},(_,i)=>new w.File(['test'],i+'.jpg',{type:'image/jpeg'}));w.addPhotos(files);assert.equal(w.document.querySelectorAll('.photo-tile').length,4);w.addPhotos([files[0]]);assert.equal(w.document.querySelectorAll('.photo-tile').length,4);assert.match(w.document.getElementById('status').textContent,/4 photos/);
 w.document.querySelectorAll('.photo-tile')[2].querySelector('button').click();assert.equal(w.eval('photoItems[0].file.name'),'2.jpg');w.document.querySelector('[aria-label="Remove photo 2"]').click();assert.equal(w.document.querySelectorAll('.photo-tile').length,3);
 // Upload/save failures remove only newly uploaded objects; successful saves survive a list refresh failure.
 w.eval(`photoItems=[{path:'products/11111111-1111-4111-8111-111111111111.jpg'},{file:new File(['x'],'new.jpg',{type:'image/jpeg'})}];imageBlob=async()=>new Blob(['x']);imageId=()=> '22222222-2222-4222-8222-222222222222';window.removed=[];db={storage:{from:()=>({upload:async()=>({error:null}),remove:async paths=>{removed.push(...paths);return {error:null}},getPublicUrl:path=>({data:{publicUrl:path}})})},from:()=>({insert:()=>({select:()=>({single:async()=>({error:{message:'Write rejected'}})})})})};`);
 await w.saveProduct({preventDefault(){}});assert.equal(w.removed.length,1);assert.ok(w.removed[0].includes('22222222'));assert.ok(!w.document.getElementById('productForm').hidden);
 w.eval(`removed=[];db.from=()=>({insert:row=>({select:()=>({single:async()=>{window.savedRow=row;return {error:null}}})})});loadAdmin=async()=>{throw Error('Offline')};`);await w.saveProduct({preventDefault(){}});assert.equal(w.removed.length,0);assert.equal(w.savedRow.image_paths.length,2);assert.equal(w.savedRow.image_path,w.savedRow.image_paths[0]);assert.ok(w.document.getElementById('productForm').hidden);
 dom.window.close();
 const c=new JSDOM(read('index.html'),{url:'https://example.test/index.html',runScripts:'outside-only',pretendToBeVisual:true});const v=c.window;v.eval=code=>require('node:vm').runInContext(code,c.getInternalVMContext());await new Promise(r=>v.setTimeout(r,0));v.scrollTo=()=>{};v.HTMLElement.prototype.scrollIntoView=()=>{};v.HTMLDialogElement.prototype.showModal=function(){this.open=true};v.HTMLDialogElement.prototype.close=function(){this.open=false};v.eval(read('customer.js'));v.eval(`cloudConfigured=true;window.KGN_CLOUD_CONFIG={url:'https://test.supabase.co'};sb={storage:{from:()=>({getPublicUrl:path=>({data:{publicUrl:'https://test.supabase.co/storage/v1/object/public/product-photos/'+path}})})}};products=[mapRow({id:'p1',image_path:'products/11111111-1111-4111-8111-111111111111.jpg',image_paths:['products/11111111-1111-4111-8111-111111111111.jpg','products/22222222-2222-4222-8222-222222222222.jpg'],name_en:'Dress',name_hi:'ड्रेस',name_ur:'لباس',category:'ladies',rate:100,sale_rate:null,unit:'piece',published:true})];`);v.eval(read('catalog-gallery.js'));v.renderAll();v.document.querySelector('[data-gallery="p1"]').click();assert.equal(v.document.getElementById('kgnGalleryCount').textContent,'1 / 2');v.document.getElementById('kgnGalleryNext').click();assert.equal(v.document.getElementById('kgnGalleryCount').textContent,'2 / 2');assert.match(v.document.getElementById('kgnGalleryImage').src,/22222222/);v.document.getElementById('kgnGalleryClose').click();
 // Exercise the real inline legacy viewer too: an image click must open only the gallery.
 const legacyViewerScript=Array.from(v.document.scripts).find(s=>s.textContent.includes('function initKgnFix()'));
 assert.ok(legacyViewerScript);v.eval(legacyViewerScript.textContent);
 v.document.querySelector('[data-gallery="p1"] img').click();
 assert.equal(v.document.querySelectorAll('dialog[open]').length,1,'A catalogue photo must not open both viewers');
 assert.ok(!v.document.getElementById('kgnPhotoViewer').open);assert.ok(v.document.querySelector('.kgn-gallery').open);
 v.document.getElementById('kgnGalleryClose').click();
 const cartPhoto=v.document.createElement('div');cartPhoto.className='cart-item';cartPhoto.innerHTML='<img src="https://example.test/cart.jpg" alt="Enquiry photo">';v.document.body.append(cartPhoto);cartPhoto.querySelector('img').click();assert.ok(v.document.getElementById('kgnPhotoViewer').open,'Enquiry photo fallback must still work');v.document.getElementById('kgnPhotoClose').click();cartPhoto.remove();
 v.eval('sb=null');v.eval(read('customer-bundles.js'));const result=v.KGNBundle.priceMarkup({sizeRates:{S:100},sizeOriginalRates:{S:200}},'S');assert.match(result,/50% off/);assert.match(result,/<del>/);assert.ok(!v.KGNBundle.priceMarkup({sizeRates:{S:100},sizeOriginalRates:{S:99}},'S').includes('<del>'));
 v.eval(read('commerce.js'));assert.ok(v.document.getElementById('kgnCheckout').hidden);assert.ok(v.document.getElementById('kgnTrackForm'));v.applyLang('ur');assert.equal(v.document.getElementById('kgnTrackTitle').textContent,'آرڈر ٹریکنگ');v.close();console.log('PASS catalogue pricing, four-photo cap/reorder/removal, rollback, persisted-save recovery, customer gallery, multilingual checkout and setup gating');
})().catch(e=>{console.error(e);process.exitCode=1});
