const {JSDOM}=require('jsdom'),fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),ts=require('typescript'),crypto=require('node:crypto');
const read=f=>fs.readFileSync(require('node:path').join(__dirname,'..',f),'utf8');
const a='11111111-1111-4111-8111-111111111111',b='22222222-2222-4222-8222-222222222222';
async function ui(){
 const dom=new JSDOM('<html lang="hi"><body><form id="kgnOrderForm"><input id="kgnBuyer" name="name"><input name="phone"><input name="address"><input name="city"><input name="pincode"></form><section id="kgnPrivacyInfo"></section></body></html>',{url:'https://example.test',runScripts:'outside-only'}),w=dom.window;
 await new Promise(r=>setTimeout(r,0));const ctx=dom.getInternalVMContext();w.safeText=v=>String(v??'').replace(/[&<>"']/g,'');w.applyLang=lang=>w.document.documentElement.lang=lang;w.confirm=()=>true;w.fakeDB={functions:{invoke:async()=>({data:{available:false}})}};vm.runInContext('const sb=window.fakeDB;',ctx);vm.runInContext(read('customer-data.js'),ctx);
 const event=p=>w.document.dispatchEvent(new w.CustomEvent('kgn:retailer-profile',{detail:p}));const profile=id=>({user_id:id,shop_name:id===a?'Shop A':'Shop B',phone:id===a?'9000000000':'9111111111',address:'10 Market Street',city:'Test city'});event(profile(a));const form=w.document.getElementById('kgnOrderForm');assert.equal(form.elements.name.value,'Shop A');assert.equal(w.localStorage.length,0);
 const remember=()=>w.document.getElementById('kgnRememberContact');remember().click();form.elements.address.value='20 Saved Road';form.elements.pincode.value='272175';form.elements.address.dispatchEvent(new w.Event('input',{bubbles:true}));assert.equal(JSON.parse(w.localStorage.getItem('kgn_customer_data_v1_'+a)).contact.address,'20 Saved Road');
 w.KGNCustomerData.saveOrder({id:a,status:'confirmed',items:[],subtotal_paise:10000,tracking_hash:'private-secret',token:'DO-NOT-BACKUP'});assert.ok(!w.localStorage.getItem('kgn_customer_data_v1_'+a).includes('DO-NOT-BACKUP'));assert.ok(!w.localStorage.getItem('kgn_customer_data_v1_'+a).includes('tracking_hash'));
 event(profile(b));assert.equal(form.elements.name.value,'Shop B');assert.equal(form.elements.address.value,'10 Market Street');assert.ok(!w.document.getElementById('kgnLocalReceipts').textContent.includes(a));event(profile(a));assert.equal(form.elements.address.value,'20 Saved Road');assert.equal(form.elements.pincode.value,'272175');
 for(const lang of ['hi','en','ur']){w.applyLang(lang);assert.equal(form.elements.address.value,'20 Saved Road');assert.ok(w.KGNCustomerData.retentionNotice().length>80)}
 const file=w.document.getElementById('kgnDataImport');Object.defineProperty(file,'files',{value:[{size:100,text:async()=>JSON.stringify({format:'kgn-customer-backup',version:1,account_id:b,contact:{name:'Wrong account'},orders:[]})}]});await file.onchange({target:file});assert.equal(form.elements.name.value,'Shop A');
 event(null);assert.equal(form.elements.name.value,'');assert.ok(!w.document.getElementById('kgnCustomerData').textContent.includes('Shop A'));w.close();console.log('PASS customer data: opt-in autosave, account isolation, persisted address, translations, receipt allowlist and wrong-account restore rejection');
}
function proofEndpoint({admin=true,status='approved',failStorage=false,failDB=false}={}){let handler,deleted=0,updated=0;const uid=a,path=b+'/proof.jpg';const db={auth:{getUser:async()=>({data:{user:{id:uid}}})},from:table=>({select:()=>{const q={eq:()=>q,maybeSingle:async()=>({data:table==='admin_users'?(admin?{user_id:uid}:null):{user_id:b,status,proof_path:path}})};return q},update:values=>{const q={eq:()=>q,select:async()=>{updated++;assert.equal(values.proof_path,'');return failDB?{error:{}}:{data:[{user_id:b}]}}};return q}}),storage:{from:bucket=>({remove:async paths=>{assert.equal(bucket,'retailer-documents');assert.deepEqual([...paths],[path]);deleted++;return failStorage?{error:{}}:{data:[]}}})}};const code=ts.transpileModule(read('supabase/functions/kgn-retailers/index.ts').replace(/^import[^\n]*\n/,''),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.None}}).outputText;vm.runInNewContext(code,{Deno:{env:{get:()=>''},serve:h=>handler=h},createClient:()=>db,crypto:crypto.webcrypto,TextEncoder,Uint8Array,Response,Request,atob});return {call:()=>handler(new Request('https://edge.test',{method:'POST',headers:{authorization:'Bearer eyJ-test'},body:JSON.stringify({action:'deleteProof',user_id:b,confirm:true})})),counts:()=>({deleted,updated})}}
async function proof(){for(const [settings,status,counts] of [[{admin:false},403,{deleted:0,updated:0}],[{status:'pending'},409,{deleted:0,updated:0}],[{failStorage:true},503,{deleted:1,updated:0}],[{failDB:true},503,{deleted:1,updated:1}],[{},200,{deleted:1,updated:1}]]){const e=proofEndpoint(settings);assert.equal((await e.call()).status,status);assert.deepEqual(e.counts(),counts)}console.log('PASS proof deletion: admin only, approved only, storage deletion before metadata, explicit failure on either stage');}
async function backup(){let handler,connection=null,stored=null,calls=[],revoked=false;const env={SUPABASE_URL:'https://edge.test',KGN_SITE_ORIGIN:'https://example.test',KGN_GOOGLE_CLIENT_ID:'public-client',KGN_GOOGLE_CLIENT_SECRET:'server-secret',KGN_BACKUP_ENCRYPTION_KEY:Buffer.alloc(32,1).toString('base64')};const db={auth:{getUser:async()=>({data:{user:{id:a}}})},from:()=>({select:()=>({eq:()=>({maybeSingle:async()=>({data:{user_id:a}})})})}),rpc:async(name,args)=>{assert.equal(name,'kgn_drive_connection');assert.equal(args.p_user,a);if(args.p_action==='set')connection={encrypted_token:args.p_token,file_id:args.p_file};if(args.p_action==='file')connection.file_id=args.p_file;if(args.p_action==='remove')connection=null;return {data:connection}}};
 const mockFetch=async(url,opts)=>{calls.push(url);if(url.includes('oauth2.googleapis.com/token')&&revoked)return Response.json({error:'invalid_grant'},{status:400});if(url.includes('oauth2.googleapis.com/token'))return Response.json({refresh_token:'PRIVATE-REFRESH',access_token:'ACCESS',scope:'https://www.googleapis.com/auth/drive.appdata'});if(url.includes('/revoke'))return new Response('{}');if(url.includes('uploadType=media')){stored=JSON.parse(opts.body);return Response.json({id:'drive-file'})}if(url.includes('uploadType=multipart')){assert.ok(opts.body.includes('\r\nContent-Type: application/json'));assert.ok(!opts.body.includes('\\r\\n'));stored=JSON.parse(opts.body.split('Content-Type: application/json\r\n\r\n')[1].split('\r\n--')[0]);return Response.json({id:'drive-file'})}if(url.includes('alt=media'))return Response.json(stored);if(url.includes('/drive/v3/files?'))return Response.json({files:[]});throw Error(url)};
 const code=ts.transpileModule(read('supabase/functions/kgn-backup/index.ts').replace(/^import[^\n]*\n/,''),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.None}}).outputText;vm.runInNewContext(code,{Deno:{env:{get:k=>env[k]},serve:h=>handler=h},createClient:()=>db,crypto:crypto.webcrypto,TextEncoder,TextDecoder,Uint8Array,Response,Request,URLSearchParams,AbortSignal,atob,btoa,fetch:mockFetch});
 const call=(body,headers={})=>handler(new Request('https://edge.test',{method:'POST',headers:{origin:'https://example.test',authorization:'Bearer eyJ-user','x-requested-with':'KGNBackup',...headers},body:JSON.stringify(body)}));
 assert.equal((await call({action:'status'},{origin:'https://evil.test'})).status,403);assert.equal((await call({action:'status'},{authorization:''})).status,401);assert.equal((await call({action:'connect',code:'CODE',consent:true})).status,200);assert.ok(!connection.encrypted_token.includes('PRIVATE-REFRESH'));
 const payload={format:'kgn-customer-backup',version:1,account_id:a,contact:{name:'Test',phone:'9000000000',password:'EXCLUDE'},orders:[],token:'EXCLUDE'};assert.equal((await call({action:'save',backup:payload})).status,200);assert.ok(!JSON.stringify(stored).includes('EXCLUDE'));const r=await (await call({action:'restore'})).json();assert.equal(r.backup.contact.name,'Test');assert.equal((await call({action:'save',backup:{...payload,account_id:b}})).status,503);assert.equal((await call({action:'save',account_id:b,backup:payload})).status,403);
 const newer={...payload,contact:{name:'Newer',phone:'9000000000',address:'Saved on first phone'},contact_updated_at:'2026-10-08T09:00:00Z',orders:[{id:a,status:'delivered',saved_at:'2026-10-08T09:00:00Z'}]};
 assert.equal((await call({action:'save',backup:newer})).status,200);
 const stale={...payload,contact:{name:'Old phone'},orders:[{id:a,status:'confirmed',saved_at:'2026-10-07T09:00:00Z'},{id:b,status:'paid',saved_at:'2026-10-07T09:00:00Z'}]};
 assert.equal((await call({action:'save',backup:stale})).status,200);assert.equal(stored.contact.address,'Saved on first phone');assert.equal(stored.orders.length,2);assert.equal(stored.orders.find(o=>o.id===a).status,'delivered');
 revoked=true;const expired=await call({action:'save',backup:payload});assert.equal(expired.status,409);assert.equal((await expired.json()).code,'reconnect_required');revoked=false;
 delete env.KGN_GOOGLE_CLIENT_SECRET;assert.equal((await (await call({action:'status'})).json()).available,false);assert.equal((await call({action:'disconnect'})).status,200);assert.equal(connection,null);console.log('PASS Drive backup: JWT/origin/CSRF checks, encrypted tokens, account binding, restricted payload, create/restore and disconnect');
}
(async()=>{await ui();await proof();await backup()})().catch(e=>{console.error(e);process.exitCode=1});
  
