import {PGlite} from '@electric-sql/pglite';
import {readFileSync,readdirSync} from 'node:fs';import assert from 'node:assert/strict';
const db=new PGlite();const owner='11111111-1111-4111-8111-111111111111',pid='22222222-2222-4222-8222-222222222222';let passed=0;
await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create schema auth;create function auth.uid() returns uuid language sql as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth to anon,authenticated;create table public.admin_users(user_id uuid primary key);insert into public.admin_users values('${owner}');grant select on public.admin_users to authenticated;
create table public.products(id uuid primary key,sku text,name_en text,name_hi text,name_ur text,image_path text,category text,unit text,rate numeric,sale_rate numeric,size_options text[],pack_options int[],size_rates jsonb,published boolean,stock_qty int);
insert into public.products values('${pid}','TEST','Test dress','टेस्ट','ٹیسٹ','products/33333333-3333-4333-8333-333333333333.jpg','ladies','piece',100,null,ARRAY['S','M'],ARRAY[3,6],'{"S":100,"M":150}',true,60);
alter table public.products enable row level security;create policy published on public.products for select using(published);create policy owner_edit on public.products for all to authenticated using(auth.uid()='${owner}') with check(auth.uid()='${owner}');grant select on public.products to anon,authenticated;grant update,insert on public.products to authenticated;
create table public.stock_audit(product_id uuid,quantity int,note text);create function public.kgn_stock_action(p_product_id uuid,p_action text,p_quantity int,p_note text) returns integer language plpgsql security definer as $$declare n int;begin if auth.uid()<>'${owner}' then raise exception 'Admin only';end if;update public.products set stock_qty=stock_qty-p_quantity where id=p_product_id and stock_qty>=p_quantity returning stock_qty into n;if n is null then raise exception 'Insufficient stock';end if;insert into public.stock_audit values(p_product_id,p_quantity,p_note);return n;end$$;`);
for(const f of readdirSync(new URL('../supabase/migrations/',import.meta.url)).sort())await db.exec(readFileSync(new URL('../supabase/migrations/'+f,import.meta.url),'utf8'));
const check=async(name,fn)=>{await fn();passed++;console.log('PASS',name)};
const rejected=async(sql,args,pattern)=>assert.rejects(()=>db.query(sql,args),pattern);
await check('legacy image preserved',async()=>assert.equal((await db.query('select cardinality(image_paths) as n from products')).rows[0].n,1));
await check('fifth image rejected by database',()=>rejected("update products set image_paths=array_fill('products/33333333-3333-4333-8333-333333333333.jpg'::text,ARRAY[5])",[],/Maximum 4/));
await check('selling price cannot exceed original',()=>rejected(`update products set size_original_rates='{"S":50}'`,[],/Original price/));
await check('valid original price accepted',async()=>{await db.exec(`update products set size_original_rates='{"S":200}'`)});
const buyer={name:'Test buyer',phone:'9000000000',address:'10 Test Road Test Market',city:'Test City',pincode:'272175'};const lines=[{id:pid,size:'S',pack:3,pieces:3,bundles:2,rate:1}];
const place=async(token,line=lines,payment='online')=>(await db.query('select kgn_place_order($1,$2,$3,$4,$5) as o',[JSON.stringify(buyer),JSON.stringify(line),payment,token,'orders-v1-20261003'])).rows[0].o;
await check('ordering disabled until merchant setup',()=>assert.rejects(()=>place('a'.repeat(64)),/not available/));
await db.exec('update kgn_commerce_settings set orders_enabled=true,online_enabled=true,cod_enabled=true');
await db.exec("set role anon");
await check('anonymous users cannot list customer orders',()=>rejected('select * from kgn_orders',[],/permission denied/));
await check('anonymous users cannot mark paid',()=>rejected("update kgn_orders set payment_status='paid'",[],/permission denied/));
await check('anonymous users cannot invoke verification',()=>rejected('select kgn_verify_payment($1,$2,$3,$4,$5)',[pid,'p','r',1,'INR'],/permission denied/));
let o;await check('server ignores caller price and computes correct total',async()=>{o=await place('a'.repeat(64));assert.equal(o.subtotal_paise,60000)});
await check('retry with same token is idempotent',async()=>assert.equal((await place('a'.repeat(64))).id,o.id));
await check('invalid size rejected',()=>assert.rejects(()=>place('b'.repeat(64),[{...lines[0],size:'XXXX'}]),/Invalid size/));
await check('invalid bundle quantity rejected',()=>assert.rejects(()=>place('b'.repeat(64),[{...lines[0],pieces:4}]),/Invalid piece/));
await check('combined sizes cannot exceed stock',()=>assert.rejects(()=>place('b'.repeat(64),[{...lines[0],bundles:15},{...lines[0],size:'M',bundles:10}]),/Combined quantity/));
await check('wrong tracking key reveals no order',()=>rejected('select kgn_track_order($1,$2)',[o.id,'b'.repeat(64)],/incorrect/));
await check('tracking omits phone and delivery address',async()=>{const x=(await db.query('select kgn_track_order($1,$2) as o',[o.id,'a'.repeat(64)])).rows[0].o;for(const k of ['phone','address','buyer_name','tracking_hash'])assert.ok(!(k in x));assert.equal(x.items[0].rate_paise,10000)});
await db.exec(`reset role;set role authenticated;set request.jwt.claim.sub='${owner}'`);
const manage=async(id,status,shipping=0)=>db.query('select kgn_manage_order($1,$2,$3,$4,$5,$6)',[id,status,shipping,'Test Courier','TEST-AWB','https://courier.example/track/TEST-AWB']);
await check('shipping charge mandatory on confirmation',()=>assert.rejects(()=>manage(o.id,'confirmed',null),/shipping/));
await check('confirmation accepts exact delivery charge',()=>manage(o.id,'confirmed',5000));
await check('online orders cannot pack before verification',()=>assert.rejects(()=>manage(o.id,'packed'),/Verified payment/));
await db.exec('reset role;set role service_role');
await check('payment claim returns server total',async()=>assert.equal((await db.query('select kgn_claim_payment_link($1) as c',[o.id])).rows[0].c.amount,65000));
await check('concurrent payment creation prevented',()=>rejected('select kgn_claim_payment_link($1)',[o.id],/reconciliation/));
await db.query("update kgn_orders set payment_link_id='plink_test',payment_link_state='ready',payment_url='https://rzp.io/test' where id=$1",[o.id]);
await check('amount mismatch cannot mark paid',()=>rejected('select kgn_verify_payment($1,$2,$3,$4,$5)',[o.id,'plink_test','pay_test',1,'INR'],/does not match/));
await check('verified payment accepted and duplicate event idempotent',async()=>{for(let i=0;i<2;i++)await db.query('select kgn_verify_payment($1,$2,$3,$4,$5)',[o.id,'plink_test','pay_test',65000,'INR']);assert.equal((await db.query("select count(*)::int as n from kgn_order_events where status='payment_verified'")).rows[0].n,1)});
await db.exec(`reset role;set role authenticated;set request.jwt.claim.sub='${owner}'`);
await check('packing succeeds after verified payment',()=>manage(o.id,'packed'));
await check('dispatch reduces stock exactly once',async()=>{await manage(o.id,'shipped');await manage(o.id,'shipped',5000);assert.equal((await db.query('select stock_qty from products')).rows[0].stock_qty,54)});
await check('cannot skip delivery stage',()=>assert.rejects(()=>manage(o.id,'delivered'),/next order stage/));
await manage(o.id,'out_for_delivery');await manage(o.id,'delivered');
await db.exec('reset role');
await check('closed order retention removes events too',async()=>{await db.query("update kgn_orders set updated_at=now()-interval '366 days' where id=$1",[o.id]);assert.equal((await db.query('select kgn_purge_closed_orders()::int as n')).rows[0].n,1);assert.equal((await db.query('select count(*)::int as n from kgn_order_events')).rows[0].n,0)});
console.log(`${passed} database/security scenarios passed`);await db.close();
