import {PGlite} from '@electric-sql/pglite';
import {readFileSync,readdirSync} from 'node:fs';import assert from 'node:assert/strict';
const db=new PGlite();const owner='11111111-1111-4111-8111-111111111111',pid='22222222-2222-4222-8222-222222222222';let passed=0;
await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create schema auth;create table auth.users(id uuid primary key,phone text,phone_confirmed_at timestamptz);create function auth.uid() returns uuid language sql as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth to anon,authenticated;create table public.admin_users(user_id uuid primary key);insert into public.admin_users values('${owner}');grant select on public.admin_users to authenticated;
create table public.products(id uuid primary key,sku text,name_en text,name_hi text,name_ur text,image_path text,category text,unit text,rate numeric,sale_rate numeric,size_options text[],pack_options int[],size_rates jsonb,published boolean,stock_qty int);
insert into public.products values('${pid}','TEST','Test dress','टेस्ट','ٹیسٹ','products/33333333-3333-4333-8333-333333333333.jpg','ladies','piece',100,null,ARRAY['S','M'],ARRAY[3,6],'{"S":100,"M":150}',true,60);
alter table public.products enable row level security;create policy published on public.products for select using(published);create policy owner_edit on public.products for all to authenticated using(auth.uid()='${owner}') with check(auth.uid()='${owner}');grant select on public.products to anon,authenticated;grant update,insert on public.products to authenticated;
create table public.stock_audit(product_id uuid,quantity int,note text);create function public.kgn_stock_action(p_product_id uuid,p_action text,p_quantity int,p_note text) returns integer language plpgsql security definer as $$declare n int;begin if auth.uid()<>'${owner}' then raise exception 'Admin only';end if;update public.products set stock_qty=stock_qty-p_quantity where id=p_product_id and stock_qty>=p_quantity returning stock_qty into n;if n is null then raise exception 'Insufficient stock';end if;insert into public.stock_audit values(p_product_id,p_quantity,p_note);return n;end$$;`);
await db.exec(`create schema private;grant usage on schema private to anon,authenticated;create function private.is_kgn_admin() returns boolean language sql security definer set search_path='' as $$select exists(select 1 from public.admin_users where user_id=auth.uid())$$;create schema storage;create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);create table storage.objects(id uuid,bucket_id text,name text);alter table storage.objects enable row level security;`);
for(const f of readdirSync(new URL('../supabase/migrations/',import.meta.url)).sort())await db.exec(readFileSync(new URL('../supabase/migrations/'+f,import.meta.url),'utf8'));
const check=async(name,fn)=>{await fn();passed++;console.log('PASS',name)};
const rejected=async(sql,args,pattern)=>assert.rejects(()=>db.query(sql,args),pattern);
await check('rollout activates retailer price boundary',async()=>assert.equal((await db.query('select retailer_access_required from kgn_commerce_settings')).rows[0].retailer_access_required,true));
// Exercise the compatible expansion period before activating access later below.
await db.exec('update kgn_commerce_settings set retailer_access_required=false');
await check('legacy image preserved',async()=>assert.equal((await db.query('select cardinality(image_paths) as n from products')).rows[0].n,1));
await check('fifth image rejected by database',()=>rejected("update products set image_paths=array_fill('products/33333333-3333-4333-8333-333333333333.jpg'::text,ARRAY[5])",[],/Maximum 4/));
await check('selling price cannot exceed original',()=>rejected(`update products set size_original_rates='{"S":50}'`,[],/Original price/));
await check('valid original price accepted',async()=>{await db.exec(`update products set size_original_rates='{"S":200}'`)});
const buyer={name:'Test buyer',phone:'9000000000',address:'10 Test Road Test Market',city:'Test City',pincode:'272175'};const lines=[{id:pid,size:'S',pack:3,pieces:3,bundles:2,rate:1}];
const place=async(token,line=lines,payment='online')=>(await db.query('select kgn_place_order($1,$2,$3,$4,$5) as o',[JSON.stringify(buyer),JSON.stringify(line),payment,token,'orders-v1-20261003'])).rows[0].o;
await check('ordering disabled until merchant setup',()=>assert.rejects(()=>place('a'.repeat(64)),/not available/));
await db.exec('update kgn_commerce_settings set orders_enabled=true,online_enabled=true,cod_enabled=true');
await db.exec("set role anon");
await check('anonymous users cannot list customer orders',()=>rejected('select * from kgn_orders',[],/permission denied/));
await check('anonymous users cannot mark paid',()=>rejected("update kgn_orders set payment_status='paid'",[],/permission denied/));
await check('anonymous users cannot invoke verification',()=>rejected('select kgn_verify_payment($1,$2,$3,$4,$5)',[pid,'p','r',1,'INR'],/permission denied/));
let o;await check('server ignores caller price and computes correct total',async()=>{o=await place('a'.repeat(64));assert.equal(o.subtotal_paise,60000)});
await check('retry with same token is idempotent',async()=>assert.equal((await place('a'.repeat(64))).id,o.id));
await check('invalid size rejected',()=>assert.rejects(()=>place('b'.repeat(64),[{...lines[0],size:'XXXX'}]),/Invalid size/));
await check('invalid bundle quantity rejected',()=>assert.rejects(()=>place('b'.repeat(64),[{...lines[0],pieces:4}]),/Invalid piece/));
await check('combined sizes cannot exceed stock',()=>assert.rejects(()=>place('b'.repeat(64),[{...lines[0],bundles:15},{...lines[0],size:'M',bundles:10}]),/Combined quantity/));
await check('wrong tracking key reveals no order',()=>rejected('select kgn_track_order($1,$2)',[o.id,'b'.repeat(64)],/incorrect/));
await check('tracking omits phone and delivery address',async()=>{const x=(await db.query('select kgn_track_order($1,$2) as o',[o.id,'a'.repeat(64)])).rows[0].o;for(const k of ['phone','address','buyer_name','tracking_hash'])assert.ok(!(k in x));assert.equal(x.items[0].rate_paise,10000)});
await db.exec(`reset role;set role authenticated;set request.jwt.claim.sub='${owner}'`);
const manage=async(id,status,shipping=0)=>db.query('select kgn_manage_order($1,$2,$3,$4,$5,$6)',[id,status,shipping,'Test Courier','TEST-AWB','https://courier.example/track/TEST-AWB']);
await check('shipping charge mandatory on confirmation',()=>assert.rejects(()=>manage(o.id,'confirmed',null),/shipping/));
await check('confirmation accepts exact delivery charge',()=>manage(o.id,'confirmed',5000));
await check('online orders cannot pack before verification',()=>assert.rejects(()=>manage(o.id,'packed'),/Verified payment/));
await db.exec('reset role;set role service_role');
await check('payment claim returns server total',async()=>assert.equal((await db.query('select kgn_claim_payment_link($1) as c',[o.id])).rows[0].c.amount,65000));
await check('concurrent payment creation prevented',()=>rejected('select kgn_claim_payment_link($1)',[o.id],/reconciliation/));
await db.query("update kgn_orders set payment_link_id='plink_test',payment_link_state='ready',payment_url='https://rzp.io/test' where id=$1",[o.id]);
await check('amount mismatch cannot mark paid',()=>rejected('select kgn_verify_payment($1,$2,$3,$4,$5)',[o.id,'plink_test','pay_test',1,'INR'],/does not match/));
await check('verified payment accepted and duplicate event idempotent',async()=>{for(let i=0;i<2;i++)await db.query('select kgn_verify_payment($1,$2,$3,$4,$5)',[o.id,'plink_test','pay_test',65000,'INR']);assert.equal((await db.query("select count(*)::int as n from kgn_order_events where status='payment_verified'")).rows[0].n,1)});
await db.exec(`reset role;set role authenticated;set request.jwt.claim.sub='${owner}'`);
await check('packing succeeds after verified payment',()=>manage(o.id,'packed'));
await check('dispatch reduces stock exactly once',async()=>{await manage(o.id,'shipped');await manage(o.id,'shipped',5000);assert.equal((await db.query('select stock_qty from products')).rows[0].stock_qty,54)});
await check('cannot skip delivery stage',()=>assert.rejects(()=>manage(o.id,'delivered'),/next order stage/));
await manage(o.id,'out_for_delivery');await manage(o.id,'delivered');
await db.exec('reset role');
await check('closed order retention removes events too',async()=>{await db.query("update kgn_orders set updated_at=now()-interval '366 days' where id=$1",[o.id]);assert.equal((await db.query('select kgn_purge_closed_orders()::int as n')).rows[0].n,0,'An old updated_at must not purge a just-delivered order');await db.query("update kgn_orders set closed_at=now()-interval '1 year',delivered_at=now()-interval '1 year' where id=$1",[o.id]);assert.equal((await db.query('select kgn_purge_closed_orders()::int as n')).rows[0].n,1);assert.equal((await db.query('select count(*)::int as n from kgn_order_events')).rows[0].n,0)});

// Direct checkout: the caller cannot supply a price, reserve unavailable stock,
// see another customer's checkout, or manufacture payment verification.
await db.exec('set role service_role');
const checkout=async(key='c'.repeat(64),line=lines,expected=60000)=>(await db.query('select kgn_prepare_checkout($1,$2,$3,$4,$5) as o',[JSON.stringify(buyer),JSON.stringify(line),key,'orders-v1-20261003',expected])).rows[0].o;
await check('direct checkout stays gated until deployment',()=>assert.rejects(()=>checkout(),/not enabled/));
await db.exec('reset role;update kgn_commerce_settings set direct_checkout_enabled=true;set role anon');
await check('anonymous cannot call privileged checkout mutations',()=>assert.rejects(()=>checkout(),/permission denied/));
await check('anonymous cannot expire somebody else stock reservation',()=>rejected('select kgn_release_expired_checkout($1,null)',[pid],/permission denied/));
await db.exec('reset role;set role service_role');
let direct;
await check('direct checkout confirms atomically without an admin and excludes courier freight',async()=>{direct=await checkout();const row=(await db.query('select status,shipping_paise,checkout_mode,delivery_payment,payment_status from kgn_orders where id=$1',[direct.id])).rows[0];assert.deepEqual(row,{status:'confirmed',shipping_paise:0,checkout_mode:'direct',delivery_payment:'courier_collect',payment_status:'unpaid'});assert.equal(direct.subtotal_paise,60000)});
await check('checkout retry reuses order and reservation',async()=>{assert.equal((await checkout()).id,direct.id);assert.equal((await db.query('select count(*)::int as n from kgn_orders')).rows[0].n,1)});
await check('stale or manipulated displayed subtotal is rejected without an order',async()=>{await assert.rejects(()=>checkout('d'.repeat(64),lines,1),/total changed/);assert.equal((await db.query('select count(*)::int as n from kgn_orders')).rows[0].n,1)});
await check('direct checkout considers stock already reserved by unpaid orders',()=>assert.rejects(()=>checkout('d'.repeat(64),[{...lines[0],bundles:17}],510000),/unreserved stock/));
await db.exec('reset role;update products set stock_qty=null;set role service_role');
await check('uncounted stock cannot be charged automatically',()=>assert.rejects(()=>checkout('d'.repeat(64)),/Stock availability/));
await db.exec('reset role;update products set stock_qty=54;set role service_role');
await check('wrong private key cannot open checkout payment',()=>rejected('select kgn_claim_checkout_payment($1,$2)',[direct.id,'e'.repeat(64)],/incorrect/));
await check('old admin link path cannot bypass direct checkout expiry',()=>rejected('select kgn_claim_payment_link($1)',[direct.id],/private customer checkout/));
await check('direct claim returns only trusted total and a bounded expiry',async()=>{const claim=(await db.query('select kgn_claim_checkout_payment($1,$2) as c',[direct.id,'c'.repeat(64)])).rows[0].c;assert.equal(claim.amount,60000);assert.ok(claim.expire_by>Date.now()/1000+1700);assert.ok(claim.expire_by<Date.now()/1000+1900)});
await check('second direct claim cannot create a duplicate payment link',()=>rejected('select kgn_claim_checkout_payment($1,$2)',[direct.id,'c'.repeat(64)],/store verification/));
await db.query("update kgn_orders set payment_link_state='ready',payment_link_id='plink_direct',payment_url='https://rzp.io/direct' where id=$1",[direct.id]);
await check('same key resumes the existing link',async()=>{const claim=(await db.query('select kgn_claim_checkout_payment($1,$2) as c',[direct.id,'c'.repeat(64)])).rows[0].c;assert.equal(claim.url,'https://rzp.io/direct');assert.equal(claim.existing,true)});
await check('direct order payment still requires exact gateway verification',async()=>{await rejected('select kgn_verify_payment($1,$2,$3,$4,$5)',[direct.id,'plink_direct','pay_direct',1,'INR'],/does not match/);await db.query('select kgn_verify_payment($1,$2,$3,$4,$5)',[direct.id,'plink_direct','pay_direct',60000,'INR'])});
await check('paid direct checkout resumes to tracking without another payment',async()=>assert.equal((await db.query('select kgn_claim_checkout_payment($1,$2) as c',[direct.id,'c'.repeat(64)])).rows[0].c.paid,true));
const abandoned=await checkout('d'.repeat(64));
await db.query("update kgn_orders set checkout_expires_at=now()-interval '36 minutes',payment_link_state='ready',payment_link_id='plink_expired' where id=$1",[abandoned.id]);
await check('expired candidates are leased once, excluding paid and manual orders',async()=>{const rows=(await db.query('select kgn_checkout_expiry_candidates() as x')).rows[0].x;assert.equal(rows.length,1);assert.equal(rows[0].id,abandoned.id);assert.deepEqual((await db.query('select kgn_checkout_expiry_candidates() as x')).rows[0].x,[])});
await check('wrong link and paid orders cannot be released',async()=>{assert.equal((await db.query('select kgn_release_expired_checkout($1,$2) as x',[abandoned.id,'plink_wrong'])).rows[0].x,false);assert.equal((await db.query('select kgn_release_expired_checkout($1,$2) as x',[direct.id,'plink_direct'])).rows[0].x,false)});
await check('gateway-confirmed expiry releases reservation without a stock sale',async()=>{assert.equal((await db.query('select kgn_release_expired_checkout($1,$2) as x',[abandoned.id,'plink_expired'])).rows[0].x,true);await db.exec('reset role');assert.equal((await db.query('select stock_qty from products')).rows[0].stock_qty,54);assert.equal((await db.query('select count(*)::int as n from stock_audit')).rows[0].n,1);await db.exec('set role service_role')});
await check('released quantity is available while paid quantity stays reserved',async()=>{await checkout('e'.repeat(64),[{...lines[0],bundles:16}],480000);await assert.rejects(()=>checkout('f'.repeat(64),[{...lines[0],bundles:1}],30000),/unreserved stock/)});
await db.exec('reset role;set role anon');
await check('private customer tracking reports courier-collect policy without contact data',async()=>{const tracked=(await db.query('select kgn_track_order($1,$2) as o',[direct.id,'c'.repeat(64)])).rows[0].o;assert.equal(tracked.delivery_payment,'courier_collect');assert.equal(tracked.payment_status,'paid');assert.equal(tracked.payment_url,null);assert.ok(!('phone' in tracked))});
const phoneUser='44444444-4444-4444-8444-444444444444',otherUser='55555555-5555-4555-8555-555555555555';
await db.exec(`reset role;update products set stock_qty=120;insert into auth.users values('${phoneUser}','919000000000',now()),('${otherUser}','919111111111',null);update kgn_commerce_settings set phone_verification_required=true;set role service_role`);
const phoneCheckout=(user=phoneUser,key='f'.repeat(64),contact=buyer)=>db.query('select kgn_prepare_phone_checkout($1,$2,$3,$4,$5,$6) as o',[JSON.stringify(contact),JSON.stringify(lines),key,'orders-v1-20261003',60000,user]);
await check('required OTP cannot be bypassed by the old direct checkout signature',()=>assert.rejects(()=>checkout('f'.repeat(64)),/Verify your mobile OTP/));
await check('a body field claiming verification is not proof',()=>assert.rejects(()=>phoneCheckout(null,'f'.repeat(64),{...buyer,phone_verified:true,phone_verified_at:new Date().toISOString()}),/Verify your mobile OTP/));
await check('unconfirmed or wrong phone identity cannot reserve stock',async()=>{await assert.rejects(()=>phoneCheckout(otherUser),/invalid for this number/);await assert.rejects(()=>phoneCheckout(phoneUser,'f'.repeat(64),{...buyer,phone:'9111111111'}),/invalid for this number/)});
await db.exec('reset role;set role anon');
await check('anonymous callers cannot spoof the privileged phone user argument',()=>assert.rejects(()=>phoneCheckout(),/permission denied/));
await check('old guest order API also requires a verified matching mobile',()=>assert.rejects(()=>place('f'.repeat(64)),/Verify your mobile OTP/));
await db.exec('reset role;set role service_role');
let verified;
await check('verified identity is recorded without changing payment verification',async()=>{verified=(await phoneCheckout()).rows[0].o;const row=(await db.query('select phone,phone_user_id,phone_verified_at,payment_status from kgn_orders where id=$1',[verified.id])).rows[0];assert.equal(row.phone,buyer.phone);assert.equal(row.phone_user_id,phoneUser);assert.ok(row.phone_verified_at);assert.equal(row.payment_status,'unpaid');assert.equal((await phoneCheckout()).rows[0].o.id,verified.id)});
await db.exec(`reset role;set role authenticated;set request.jwt.claim.sub='${phoneUser}'`);
await check('a phone customer cannot read the admin order list',async()=>assert.deepEqual((await db.query('select * from kgn_orders')).rows,[]));
await check('verified COD uses the matching signed identity',async()=>{const result=await place('1'.repeat(64),lines,'cod');assert.equal(result.status,'requested')});
await db.exec(`reset role;set role authenticated;set request.jwt.claim.sub='${otherUser}'`);
await check('a different signed phone cannot place a legacy order',()=>assert.rejects(()=>place('2'.repeat(64)),/Verify your mobile OTP/));
await db.exec('reset role;set role anon');
await check('verified customer tracking still omits mobile, address and Auth identity',async()=>{const tracked=(await db.query('select kgn_track_order($1,$2) as o',[verified.id,'f'.repeat(64)])).rows[0].o;for(const key of ['phone','address','phone_user_id','phone_verified_at'])assert.ok(!(key in tracked))});

await db.exec(`reset role;update kgn_commerce_settings set retailer_access_required=true,phone_verification_required=false;insert into kgn_retailers(user_id,phone,shop_name,contact_name,address,city,proof_path) values('${phoneUser}','9000000000','Test shop','Test owner','Test shop street 123','Test city','${phoneUser}/proof.jpg');`);
await db.exec('set role anon');
await check('price boundary hides all product columns from guests',async()=>assert.deepEqual((await db.query('select rate,size_rates,image_paths from products')).rows,[]));
await check('legacy order RPC cannot reveal totals to guests after rollout',()=>assert.rejects(()=>place('3'.repeat(64)),/Retailer approval/));
await check('guest cannot read retailer applications',()=>assert.rejects(()=>db.query('select * from kgn_retailers'),/permission denied/));
await db.exec(`reset role;set role authenticated;set request.jwt.claim.sub='${phoneUser}'`);
await check('pending retailer cannot fetch prices',async()=>assert.deepEqual((await db.query('select * from products')).rows,[]));
await check('retailer cannot approve their own application',async()=>{await db.query("update kgn_retailers set status='approved' where user_id=$1",[phoneUser]);assert.equal((await db.query('select status from kgn_retailers')).rows[0].status,'pending')});
await check('retailer cannot edit registered phone or replace identity',()=>assert.rejects(()=>db.query("update kgn_retailers set phone='9111111111'"),/permission denied/));
await db.exec(`reset role;set role authenticated;set request.jwt.claim.sub='${owner}'`);
await check('owner retains full product and inventory listing',async()=>assert.equal(Number((await db.query('select rate from products')).rows[0].rate),100));
await check('owner can approve a retailer',async()=>{await db.query("update kgn_retailers set status='approved' where user_id=$1",[phoneUser]);});
await db.exec(`reset role;set role authenticated;set request.jwt.claim.sub='${phoneUser}'`);
await check('approved retailer can fetch original rates',async()=>assert.equal((await db.query('select size_rates from products')).rows[0].size_rates.S,100));
await check('approved retailer cannot edit inventory or prices',async()=>{await db.query('update products set rate=1 where id=$1',[pid]);assert.equal(Number((await db.query('select rate from products')).rows[0].rate),100)});
await db.exec(`reset role;update kgn_retailers set status='blocked' where user_id='${phoneUser}';set role authenticated;set request.jwt.claim.sub='${phoneUser}'`);
await check('blocking access takes effect on the existing identity',async()=>assert.deepEqual((await db.query('select * from products')).rows,[]));
await db.exec('reset role');
await check('blocked retailer cannot use service checkout wrapper',()=>assert.rejects(()=>db.query('select kgn_prepare_retailer_checkout($1,$2,$3,$4,$5,$6,$7)',[JSON.stringify(buyer),JSON.stringify(lines),'4'.repeat(64),'orders-v1-20261003',60000,null,phoneUser]),/Retailer approval/));

await db.exec(`insert into public.kgn_orders(id,tracking_hash,buyer_name,phone,address,city,pincode,items,subtotal_paise,shipping_paise,status,payment_method,payment_status,policy_version,closed_at,delivered_at,retention_hold)
 select ('aaaaaaaa-aaaa-4aaa-8aaa-'||lpad(n::text,12,'0'))::uuid,sha256(convert_to('retention-'||n,'UTF8')),'Private Customer','9000000000','Private shop address','City','272175','[]',10000,0,
 case when n=4 then 'confirmed' when n=5 then 'cancelled' else 'delivered' end,'online','paid','orders-v1-20261003',
 case when n=3 then now()-interval '1 year'+interval '1 day' else now()-interval '1 year' end,now()-interval '1 year',n=2 from generate_series(1,5)n;
 insert into public.kgn_order_events(order_id,status) values('aaaaaaaa-aaaa-4aaa-8aaa-000000000001','delivered');`);
await check('retention switch off preserves all eligible records',async()=>{await db.exec('update kgn_commerce_settings set order_retention_enabled=false');assert.equal((await db.query('select kgn_purge_closed_orders()::int n')).rows[0].n,0);await db.exec('update kgn_commerce_settings set order_retention_enabled=true')});
await check('one year cleanup removes eligible delivered and cancelled orders only',async()=>{assert.equal((await db.query('select kgn_purge_closed_orders()::int n')).rows[0].n,2);const ids=(await db.query("select id from kgn_orders where id::text like 'aaaaaaaa-%' order by id")).rows.map(r=>r.id.slice(-1));assert.deepEqual(ids,['2','3','4']);assert.equal((await db.query("select count(*)::int n from kgn_order_events where order_id='aaaaaaaa-aaaa-4aaa-8aaa-000000000001'")).rows[0].n,0)});
await check('payment archive excludes all contact, line items and private tracking keys',async()=>{const r=(await db.query("select to_jsonb(t) row from private.kgn_payment_receipts t where order_id='aaaaaaaa-aaaa-4aaa-8aaa-000000000001'")).rows[0].row;assert.equal(r.subtotal_paise,10000);for(const k of ['buyer_name','phone','address','items','tracking_hash','retailer_user_id'])assert.ok(!(k in r));assert.equal((await db.query('select kgn_purge_closed_orders()::int n')).rows[0].n,0)});
await db.exec(`set role authenticated;set request.jwt.claim.sub='${phoneUser}'`);
await check('retailer cannot disable cleanup or alter another order hold',async()=>{await db.exec('update kgn_commerce_settings set order_retention_enabled=false');assert.equal((await db.query('select order_retention_enabled from kgn_commerce_settings')).rows[0].order_retention_enabled,true);assert.equal((await db.query("update kgn_orders set retention_hold=false returning id")).rows.length,0)});
await check('customer cannot read encrypted Drive connections or call their service RPC',async()=>{await assert.rejects(()=>db.query('select * from private.kgn_drive_connections'),/permission denied/);await assert.rejects(()=>db.query('select kgn_drive_connection($1,$2)',[phoneUser,'get']),/permission denied/)});
await check('owner-facing proof deletion cannot be forged by editing proof_path',()=>assert.rejects(()=>db.query("update kgn_retailers set proof_path=''"),/permission denied/));
await db.exec('reset role');
console.log(`${passed} database/security scenarios passed`);
await db.close();
  
