const {JSDOM}=require('jsdom'),fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),ts=require('typescript'),crypto=require('node:crypto');
const read=f=>fs.readFileSync(require('node:path').join(__dirname,'..',f),'utf8');
const product={id:'p1',sku:'QA',name_hi:'ड्रेस',name_en:'Dress',name_ur:'لباس',category:'ladies',published:true,is_new:true,unit:'piece',moq:3,size_options:['S'],pack_options:[3],public_image_paths:['products/public.jpg']};
function endpoint(status,invalid=false){let handler;const selected=[];const db={auth:{getUser:async()=>invalid?{error:{},data:{}}:{data:{user:{id:'retailer'}}}},from:table=>({select:fields=>{selected.push({table,fields});const q={eq:()=>q,order:()=>q,limit:async()=>({data:[Object.fromEntries(Object.entries({...product,rate:110,sale_rate:null,size_rates:{S:110},size_original_rates:{S:150},stock_qty:20,image_path:'products/original.jpg'}).filter(([k])=>fields.split(',').includes(k)))]}),maybeSingle:async()=>({data:table==='kgn_retailers'&&status?{status,shop_name:'Test shop'}:null})};return q}}),storage:{from:bucket=>({getPublicUrl:path=>({data:{publicUrl:bucket+'/'+path}}),createSignedUrls:async paths=>({data:paths.map(path=>({signedUrl:'signed/'+path}))})})}};
 const src=read('supabase/functions/kgn-retailers/index.ts').replace(/^import[^\n]*\n/,'');vm.runInNewContext(ts.transpileModule(src,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.None}}).outputText,{Deno:{env:{get:()=>''},serve:h=>handler=h},createClient:()=>db,crypto:crypto.webcrypto,TextEncoder,Uint8Array,Response,Request,atob});return {handler,selected};}
async function edge(){for(const status of [null,'pending','approved','rejected','blocked']){const f=endpoint(status),res=await f.handler(new Request('https://example.test',{method:'POST',headers:status?{authorization:'Bearer eyJ-test'}:{},body:JSON.stringify({action:'catalog'})}));assert.equal(res.status,200);const data=await res.json();assert.equal(data.approved,status==='approved');const row=data.products[0];assert.ok(!('image_path'in row));assert.ok(!('public_image_paths'in row));if(status==='approved'){assert.equal(row.rate,110);assert.deepEqual(row.size_rates,{S:110});assert.match(row.image_urls[0],/^signed\//)}else{assert.equal(row.rate,null);assert.deepEqual(row.size_rates,{});assert.equal(row.stock_qty,null);assert.match(row.image_urls[0],/^public-catalogue\//);assert.ok(!f.selected.find(x=>x.table==='products').fields.split(',').includes('rate'))}}
 const f=endpoint('approved',true);assert.equal((await f.handler(new Request('https://example.test',{method:'POST',headers:{authorization:'Bearer eyJ-invalid'},body:'{"action":"catalog"}'}))).status,401);
 console.log('PASS retailer endpoint: public projection, approval states, private signed photos and invalid-session rejection');}
async function ui(){const dom=new JSDOM(read('index.html'),{url:'https://example.test',runScripts:'outside-only',pretendToBeVisual:true}),w=dom.window;w.eval=s=>vm.runInContext(s,dom.getInternalVMContext());await new Promise(r=>w.setTimeout(r,0));w.scrollTo=()=>{};w.HTMLElement.prototype.scrollIntoView=()=>{};w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};w.eval(read('customer.js'));let status=null;
 w.fakeDB={functions:{invoke:async()=>({data:{approved:status==='approved',profile:status?{status,shop_name:'Test shop',phone:'9000000000'}:null,products:[{...product,rate:status==='approved'?110:null,sale_rate:null,size_rates:status==='approved'?{S:110}:{},size_original_rates:{},image_urls:['https://test.supabase.co/storage/v1/object/public/public-catalogue/products/public.jpg']}]}})},from:()=>({select:()=>({eq:()=>({maybeSingle:async()=>({data:{festive_enabled:true}})})})}),auth:{signInWithPassword:async args=>{assert.equal(args.email,'retailer.9000000000@kgn-login.invalid');status='pending';return {}},signOut:async()=>{status=null}}};w.eval('sb=window.fakeDB;cloudConfigured=true;window.KGN_CLOUD_CONFIG={url:"https://test.supabase.co"};');for(const f of ['customer-bundles.js','catalog-gallery.js','retailer-access.js'])w.eval(read(f));await w.refreshCloud();const $=id=>w.document.getElementById(id);
 assert.equal(w.KGNRetailer.allowed(),false);assert.ok([...w.document.querySelectorAll('.price-row')].every(el=>!el.textContent.includes('₹')));w.document.querySelector('[data-add="p1"]').click();assert.ok($('kgnRetailerDialog').open);assert.ok(!$('kgnBundleDialog').open);$('kgnRetailerPhone').value='9000000000';$('kgnRetailerPassword').value='TestPassword1';await $('kgnRetailerForm').onsubmit({preventDefault(){}});assert.equal(w.KGNRetailer.profile().status,'pending');assert.ok(!$('kgnRetailerForm'));$('kgnRetailerClose').click();status='approved';await w.KGNRetailer.refresh();assert.equal(w.KGNRetailer.allowed(),true);w.document.querySelector('[data-add="p1"]').click();assert.ok($('kgnBundleDialog').open);$('kgnBundleClose').click();assert.match(w.document.querySelector('.price-row').textContent,/110/);w.document.querySelector('[data-gallery="p1"]').click();assert.ok(w.document.querySelector('.kgn-gallery').open);status='blocked';await w.KGNRetailer.refresh();assert.ok(!w.document.querySelector('.kgn-gallery').open);assert.ok([...w.document.querySelectorAll('.price-row')].every(el=>!el.textContent.includes('110')));for(const lang of ['hi','en','ur']){w.applyLang(lang);w.KGNRetailer.open();assert.ok($('kgnRetailerDialog').textContent.includes('Test shop'));$('kgnRetailerClose').click()}w.close();console.log('PASS retailer UI: guest gate, mobile login, pending approval, unlocked bundle/gallery and blocked access in three languages');}
(async()=>{await edge();await ui()})().catch(e=>{console.error(e);process.exit(1)});
